import django.db.models.deletion
import django.utils.timezone
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ordering", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="knowledge_engine.knowledgecategory")),
            ],
            options={"db_table": "knowledge_categories", "ordering": ["ordering", "name"]},
        ),
        migrations.AddConstraint(
            model_name="knowledgecategory",
            constraint=models.UniqueConstraint(fields=("name", "parent"), name="uniq_knowledge_category_name_parent"),
        ),
        migrations.CreateModel(
            name="EquipmentReference",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("equipment_type", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "knowledge_equipment_references", "ordering": ["manufacturer", "name"]},
        ),
        migrations.CreateModel(
            name="SymptomReference",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                ("severity_level", models.CharField(blank=True, choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "knowledge_symptom_references", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="FailureReference",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("criticality", models.CharField(blank=True, choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "knowledge_failure_references", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="CauseReference",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                ("cause_type", models.CharField(blank=True, choices=[("electrical", "Electrical"), ("mechanical", "Mechanical"), ("human", "Human"), ("operational", "Operational"), ("environmental", "Environmental"), ("other", "Other")], max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "knowledge_cause_references", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="RecommendedAction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                ("action_type", models.CharField(choices=[("inspection", "Inspection"), ("repair", "Repair"), ("replacement", "Replacement"), ("cleaning", "Cleaning"), ("calibration", "Calibration"), ("monitoring", "Monitoring")], default="inspection", max_length=20)),
                ("priority", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")], default="medium", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "knowledge_recommended_actions", "ordering": ["title"]},
        ),
        migrations.CreateModel(
            name="TroubleshootingArticle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "Review"), ("published", "Published"), ("archived", "Archived")], default="draft", max_length=20)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="articles", to="knowledge_engine.knowledgecategory")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="knowledge_articles_created", to=settings.AUTH_USER_MODEL)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="knowledge_articles_reviewed", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "knowledge_troubleshooting_articles", "ordering": ["-published_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="TechnicalDocument",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("document_type", models.CharField(choices=[("manual", "Manual"), ("service_manual", "Service Manual"), ("datasheet", "Datasheet"), ("procedure", "Procedure"), ("checklist", "Checklist"), ("technical_bulletin", "Technical Bulletin")], max_length=30)),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("version", models.CharField(blank=True, max_length=40)),
                ("file", models.FileField(blank=True, null=True, upload_to="knowledge_engine/documents/")),
                ("external_url", models.URLField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "Review"), ("published", "Published"), ("archived", "Archived")], default="draft", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="technical_documents", to="knowledge_engine.knowledgecategory")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="technical_documents_created", to=settings.AUTH_USER_MODEL)),
                ("equipment_reference", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="technical_documents", to="knowledge_engine.equipmentreference")),
            ],
            options={"db_table": "knowledge_technical_documents", "ordering": ["title"]},
        ),
        migrations.CreateModel(
            name="KnowledgeTag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "knowledge_tags", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="KnowledgeLinkRule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("source_type", models.CharField(choices=[("equipment", "Equipment"), ("symptom", "Symptom"), ("failure", "Failure"), ("cause", "Cause"), ("action", "Action"), ("article", "Article"), ("document", "Document")], max_length=30)),
                ("source_id", models.PositiveBigIntegerField()),
                ("target_type", models.CharField(choices=[("equipment", "Equipment"), ("symptom", "Symptom"), ("failure", "Failure"), ("cause", "Cause"), ("action", "Action"), ("article", "Article"), ("document", "Document")], max_length=30)),
                ("target_id", models.PositiveBigIntegerField()),
                ("relation_type", models.CharField(choices=[("symptom_indicates_failure", "Symptom Indicates Failure"), ("failure_has_cause", "Failure Has Cause"), ("failure_recommended_action", "Failure Recommended Action"), ("equipment_has_document", "Equipment Has Document"), ("article_relates_equipment", "Article Relates Equipment")], max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "knowledge_link_rules", "ordering": ["relation_type", "-created_at"]},
        ),
        migrations.CreateModel(
            name="EquipmentSymptomMap",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("confidence_level", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("equipment_reference", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="symptom_maps", to="knowledge_engine.equipmentreference")),
                ("symptom_reference", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="equipment_maps", to="knowledge_engine.symptomreference")),
            ],
            options={"db_table": "knowledge_equipment_symptom_maps"},
        ),
        migrations.AddConstraint(
            model_name="equipmentsymptommap",
            constraint=models.UniqueConstraint(fields=("equipment_reference", "symptom_reference"), name="uniq_equipment_symptom_map"),
        ),
        migrations.CreateModel(
            name="SymptomFailureMap",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("confidence_level", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("failure_reference", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="symptom_maps", to="knowledge_engine.failurereference")),
                ("symptom_reference", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="failure_maps", to="knowledge_engine.symptomreference")),
            ],
            options={"db_table": "knowledge_symptom_failure_maps"},
        ),
        migrations.AddConstraint(
            model_name="symptomfailuremap",
            constraint=models.UniqueConstraint(fields=("symptom_reference", "failure_reference"), name="uniq_symptom_failure_map"),
        ),
        migrations.CreateModel(
            name="FailureCauseMap",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("confidence_level", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cause_reference", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="failure_maps", to="knowledge_engine.causereference")),
                ("failure_reference", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cause_maps", to="knowledge_engine.failurereference")),
            ],
            options={"db_table": "knowledge_failure_cause_maps"},
        ),
        migrations.AddConstraint(
            model_name="failurecausemap",
            constraint=models.UniqueConstraint(fields=("failure_reference", "cause_reference"), name="uniq_failure_cause_map"),
        ),
        migrations.CreateModel(
            name="FailureActionMap",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("priority", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("failure_reference", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="action_maps", to="knowledge_engine.failurereference")),
                ("recommended_action", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="failure_maps", to="knowledge_engine.recommendedaction")),
            ],
            options={"db_table": "knowledge_failure_action_maps"},
        ),
        migrations.AddConstraint(
            model_name="failureactionmap",
            constraint=models.UniqueConstraint(fields=("failure_reference", "recommended_action"), name="uniq_failure_action_map"),
        ),
        migrations.CreateModel(
            name="KnowledgeFeedback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("item_type", models.CharField(choices=[("article", "Article"), ("document", "Document"), ("equipment", "Equipment"), ("failure", "Failure"), ("action", "Action")], max_length=20)),
                ("item_id", models.PositiveBigIntegerField()),
                ("usefulness_rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="knowledge_feedbacks", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "knowledge_feedbacks", "ordering": ["-created_at"]},
        ),
    ]
