# Generated by Django 6.0.4 on 2026-05-19 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiviaConversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=120)),
                ('visitor_name', models.CharField(blank=True, max_length=150)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('visitor_phone', models.CharField(blank=True, max_length=40)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('open', 'Open'), ('qualified', 'Qualified'), ('handed_off', 'Handed off'), ('closed', 'Closed')], default='open', max_length=20)),
                ('source_page', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'livia_conversations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', 'status'], name='livia_conve_session_8a43a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiviaHandoffRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_requests', to='livia_assistant.liviaconversation')),
            ],
            options={
                'db_table': 'livia_handoff_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiviaLeadCapture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=180)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('service_interest', models.CharField(blank=True, max_length=180)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_qualified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_captures', to='livia_assistant.liviaconversation')),
            ],
            options={
                'db_table': 'livia_lead_captures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiviaMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='livia_assistant.liviaconversation')),
            ],
            options={
                'db_table': 'livia_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
