# Generated by Django 6.0.4 on 2026-05-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livia_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiviaKnowledgeItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('services', 'Services'), ('company', 'Company'), ('pricing_policy', 'Pricing policy'), ('safety', 'Safety'), ('faq', 'FAQ'), ('process', 'Process'), ('technical', 'Technical'), ('smart360', 'Smart360')], max_length=30)),
                ('content', models.TextField()),
                ('keywords', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'livia_knowledge_items',
                'ordering': ['-priority', 'title'],
            },
        ),
    ]
