# Generated by Django 6.0.4 on 2026-05-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livia_assistant', '0002_liviaknowledgeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='livialeadcapture',
            name='crm_lead_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livialeadcapture',
            name='crm_reference',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='livialeadcapture',
            name='operational_status',
            field=models.CharField(choices=[('new', 'New'), ('sent_to_crm', 'Sent to CRM'), ('contacted', 'Contacted'), ('lost', 'Lost'), ('converted', 'Converted')], default='new', max_length=20),
        ),
    ]
