# Generated by Django 6.0.4 on 2026-06-12 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livia_assistant', '0003_livialeadcapture_crm_lead_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiviaKnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('source_type', models.CharField(default='markdown', max_length=40)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('product', models.CharField(blank=True, db_index=True, max_length=120)),
                ('application', models.CharField(blank=True, db_index=True, max_length=120)),
                ('source_path', models.CharField(max_length=500, unique=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'livia_knowledge_documents',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LiviaKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='livia_assistant.liviaknowledgedocument')),
            ],
            options={
                'db_table': 'livia_knowledge_chunks',
                'ordering': ['document_id', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='livia_unique_document_chunk_index')],
            },
        ),
    ]
