import django.db.models.deletion
import django.utils.timezone
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "smart_system_asset_categories", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "smart_system_checklists", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="MaintenanceClient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("display_name", models.CharField(max_length=180)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("document_number", models.CharField(blank=True, max_length=40)),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_clients", to="companies.company")),
            ],
            options={"db_table": "smart_system_clients", "ordering": ["display_name"]},
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("item_type", models.CharField(choices=[("boolean", "Boolean"), ("text", "Text"), ("number", "Number"), ("choice", "Choice")], default="boolean", max_length=20)),
                ("ordering", models.PositiveIntegerField(default=1)),
                ("is_required", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checklist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="smart_system.checklist")),
            ],
            options={"db_table": "smart_system_checklist_items", "ordering": ["checklist__name", "ordering", "id"]},
        ),
        migrations.CreateModel(
            name="OperationalSite",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("code", models.CharField(blank=True, max_length=40)),
                ("address_line", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("maintenance_client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="operational_sites", to="smart_system.maintenanceclient")),
            ],
            options={"db_table": "smart_system_operational_sites", "ordering": ["maintenance_client__display_name", "name"]},
        ),
        migrations.AddConstraint(
            model_name="operationalsite",
            constraint=models.UniqueConstraint(fields=("maintenance_client", "name"), name="uniq_smart_system_site_name_per_client"),
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("asset_tag", models.CharField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("serial_number", models.CharField(blank=True, max_length=120)),
                ("voltage", models.CharField(blank=True, max_length=50)),
                ("power_rating", models.CharField(blank=True, max_length=50)),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("warranty_until", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("operating", "Operating"), ("maintenance", "Maintenance"), ("stopped", "Stopped"), ("decommissioned", "Decommissioned")], default="operating", max_length=20)),
                ("criticality", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="medium", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="smart_system.assetcategory")),
                ("operational_site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assets", to="smart_system.operationalsite")),
            ],
            options={"db_table": "smart_system_assets", "ordering": ["operational_site__name", "asset_tag"]},
        ),
        migrations.CreateModel(
            name="MaintenancePlan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("frequency_type", models.CharField(choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly"), ("custom", "Custom")], default="monthly", max_length=20)),
                ("frequency_value", models.PositiveIntegerField(default=1)),
                ("estimated_duration_minutes", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("last_generated_at", models.DateTimeField(blank=True, null=True)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="maintenance_plans", to="smart_system.asset")),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="maintenance_plans", to="smart_system.assetcategory")),
                ("checklist", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_plans", to="smart_system.checklist")),
            ],
            options={"db_table": "smart_system_maintenance_plans", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("order_number", models.CharField(max_length=40, unique=True)),
                ("maintenance_type", models.CharField(choices=[("preventive", "Preventive"), ("corrective", "Corrective"), ("inspection", "Inspection"), ("installation", "Installation")], max_length=20)),
                ("priority", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")], default="medium", max_length=20)),
                ("status", models.CharField(choices=[("open", "Open"), ("scheduled", "Scheduled"), ("in_progress", "In Progress"), ("on_hold", "On Hold"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="open", max_length=20)),
                ("source", models.CharField(choices=[("manual", "Manual"), ("plan", "Maintenance Plan"), ("alert", "Alert"), ("failure", "Failure")], default="manual", max_length=20)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("requested_by", models.CharField(blank=True, max_length=150)),
                ("final_observations", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="service_orders", to="smart_system.asset")),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_service_orders", to=settings.AUTH_USER_MODEL)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="service_orders", to="smart_system.maintenanceclient")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_service_orders", to=settings.AUTH_USER_MODEL)),
                ("maintenance_plan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="service_orders", to="smart_system.maintenanceplan")),
                ("operational_site", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="service_orders", to="smart_system.operationalsite")),
            ],
            options={"db_table": "smart_system_service_orders", "ordering": ["-opened_at"]},
        ),
        migrations.CreateModel(
            name="FailureEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("detected_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("symptom", models.TextField()),
                ("probable_cause", models.TextField(blank=True)),
                ("root_cause", models.TextField(blank=True)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="medium", max_length=20)),
                ("downtime_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("analyzing", "Analyzing"), ("resolved", "Resolved"), ("monitored", "Monitored")], default="open", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="failure_events", to="smart_system.asset")),
                ("service_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="failure_events", to="smart_system.serviceorder")),
            ],
            options={"db_table": "smart_system_failure_events", "ordering": ["-detected_at"]},
        ),
        migrations.CreateModel(
            name="AssetHistoryEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("event_type", models.CharField(choices=[("service_order_created", "Service Order Created"), ("service_order_completed", "Service Order Completed"), ("failure_reported", "Failure Reported"), ("status_changed", "Status Changed"), ("general", "General")], default="general", max_length=40)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history_events", to="smart_system.asset")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="asset_history_events", to=settings.AUTH_USER_MODEL)),
                ("related_failure_event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="asset_history_events", to="smart_system.failureevent")),
                ("related_service_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="asset_history_events", to="smart_system.serviceorder")),
            ],
            options={"db_table": "smart_system_asset_history_events", "ordering": ["-occurred_at"]},
        ),
        migrations.CreateModel(
            name="ServiceOrderChecklistResponse",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("response_boolean", models.BooleanField(blank=True, null=True)),
                ("response_text", models.TextField(blank=True)),
                ("response_number", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("response_choice", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checklist_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="responses", to="smart_system.checklistitem")),
                ("service_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checklist_responses", to="smart_system.serviceorder")),
            ],
            options={"db_table": "smart_system_so_checklist_responses", "ordering": ["checklist_item__ordering", "id"]},
        ),
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("labor_minutes", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="work_logs", to="smart_system.serviceorder")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="work_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "smart_system_work_logs", "ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="ServiceDocument",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("file", models.FileField(upload_to="smart_system/documents/")),
                ("document_type", models.CharField(choices=[("photo", "Photo"), ("report", "Report"), ("invoice", "Invoice"), ("other", "Other")], default="other", max_length=20)),
                ("title", models.CharField(max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="smart_system.serviceorder")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="service_documents", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "smart_system_service_documents", "ordering": ["-created_at"]},
        ),
    ]
