# Generated by Django 6.0.4 on 2026-05-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_system', '0012_phase1_equipment_catalog_and_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('adjustment', 'Adjustment'), ('reserved', 'Reserved')], max_length=20),
        ),
    ]
