# Generated by Django 6.0.4 on 2026-05-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_system', '0014_preventive_inspection_rotation_phase1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiondivision',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inspectiondivisionequipment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preventiveinspectionroutine',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
