# Generated by Django 6.0.4 on 2026-05-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability_center', '0002_request_trace_and_context_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorincident',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobexecutiontrace',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metriccounter',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemeventlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
