# Generated by Django 6.0.4 on 2026-05-21 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoria técnica',
                'verbose_name_plural': 'categorias técnicas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], default='basic', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='technical_portal.technicalcategory')),
            ],
            options={
                'verbose_name': 'artigo técnico',
                'verbose_name_plural': 'artigos técnicos',
                'ordering': ['category__order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('code', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=180)),
                ('probable_cause', models.TextField()),
                ('recommended_action', models.TextField()),
                ('safety_warning', models.TextField(blank=True)),
                ('source_note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='error_codes', to='technical_portal.technicalcategory')),
            ],
            options={
                'verbose_name': 'código de erro',
                'verbose_name_plural': 'códigos de erro',
                'ordering': ['category__order', 'equipment_type', 'code'],
            },
        ),
    ]
