[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
python_classes = Test* *Tests
python_functions = test_*
testpaths = tests apps
addopts = -ra
markers =
    smoke: smoke tests rapidos para validar disponibilidade da plataforma
    api: testes de API REST
    integration: testes de integracao entre bounded contexts
    unit: testes unitarios

