from django.urls import include, path

from apps.growth_engine.dashboard_views import (
    GrowthApprovedProposalsListView,
    GrowthCommercialProposalActionView,
    GrowthCommercialProposalOperationalForwardView,
    GrowthLeadActionView,
    GrowthLeadCreateProposalView,
    GrowthLeadDetailView,
    GrowthLiviaLeadListView,
    GrowthMarketplaceLeadCreateProposalView,
    GrowthMarketplaceLeadDetailView,
    GrowthMarketplaceLeadListView,
    GrowthProposalDetailView,
)
from apps.media_library.dashboard_views import (
    MediaAssetCreateView,
    MediaAssetDeactivateView,
    MediaAssetDetailView,
    MediaAssetListView,
    MediaAssetUpdateView,
)
from apps.livia_assistant.dashboard_views import (
    LiviaConversationDetailView,
    LiviaConversationListView,
    LiviaDashboardView,
    LiviaHandoffListView,
    LiviaKnowledgeCreateView,
    LiviaKnowledgeListView,
    LiviaKnowledgeUpdateView,
    LiviaLeadActionView,
    LiviaLeadDetailView,
    LiviaLeadListView,
)

from .views import (
    AIAgentActionProposalsView,
    AIAgentAnomalyHealthView,
    AIAgentMaintenanceHealthView,
    AIAgentMarketplaceHealthView,
    AIAgentProfitabilityHealthView,
    AIAutonomyCenterView,
    AIDigitalTwinCenterView,
    AIKnowledgeGraphCenterView,
    AIVoiceOpsCenterView,
    AIDecisionApproveView,
    AIDecisionRejectView,
    AIAgentProposalApproveView,
    AIAgentProposalRejectView,
    AIAgentRecommendationsView,
    AIAgentRunsView,
    AIExperimentationCenterView,
    AIAgentSchedulingHealthView,
    AIOptimizationCenterView,
    AIPolicyStudioView,
    AISimulationCenterView,
    AIBriefingDetailView,
    AIBriefingGenerateView,
    AIBriefingListView,
    AIManagerCopilotView,
    AIAgentsDashboardView,
    AnalyticsExecutiveDashboardView,
    AnalyticsExecutiveRefreshView,
    BillingAdminDashboardView,
    BillingContractCancelView,
    BillingContractDetailView,
    BillingContractListView,
    BillingContractSuspendView,
    BillingInvoiceCancelView,
    BillingInvoiceListView,
    BillingInvoiceMarkPaidView,
    BillingPlanListView,
    ClientPortalAssetDetailView,
    ClientPortalAssetListView,
    ClientPortalBriefingDetailView,
    ClientPortalContractDetailView,
    ClientPortalContractListView,
    ClientPortalCopilotContextView,
    ClientPortalCopilotPendingItemsView,
    ClientPortalCopilotQueryView,
    ClientPortalCopilotSuggestionsView,
    ClientPortalCopilotView,
    ClientPortalDashboardView,
    ClientPortalPreventiveDetailView,
    ClientPortalPreventiveListView,
    ClientPortalProfileView,
    ClientPortalQuoteApproveView,
    ClientPortalQuoteDetailView,
    ClientPortalQuoteListView,
    ClientPortalQuoteRejectView,
    ClientPortalReportDownloadView,
    ClientPortalReportListView,
    ClientPortalReportPreviewView,
    ClientPortalRequestCreateView,
    ClientPortalRequestDetailView,
    ClientPortalRequestListView,
    ClientPortalSitesView,
    ClientPortalWorkOrderDetailView,
    ClientPortalWorkOrderListView,
    DashboardView,
    ExecutiveWarRoomDataView,
    ExecutiveWarRoomRealtimeStreamView,
    ExecutiveWarRoomView,
    MarketplaceTechnicianDetailView,
    MarketplaceTechniciansAssignmentListView,
    MarketplaceTechniciansDashboardView,
    MarketplaceTechniciansMatchingListView,
    MarketplaceTechniciansOfferListView,
    MarketplaceTechniciansRequestListView,
    MarketplaceTechniciansReviewListView,
    MarketplaceTechniciansTechnicianListView,
    ModulePageView,
    ObservabilityDashboardView,
    SetActiveContextView,
    SmartSystemAssetDetailView,
    SmartSystemAssetListView,
    SmartSystemOperationsView,
    SmartSystemReliabilityView,
    SmartSystemCustomerEquipmentCreateView,
    SmartSystemCustomerEquipmentDetailView,
    SmartSystemCustomerEquipmentListView,
    SmartSystemCustomerEquipmentUpdateView,
    SmartSystemCustomerCreateView,
    SmartSystemCustomerDetailView,
    SmartSystemCustomerListView,
    SmartSystemCustomerUpdateView,
    SmartSystemEquipmentModelCreateView,
    SmartSystemEquipmentModelDetailView,
    SmartSystemEquipmentModelListView,
    SmartSystemEquipmentModelUpdateView,
    SmartSystemChecklistDetailView,
    SmartSystemChecklistDeactivateView,
    SmartSystemChecklistCreateView,
    SmartSystemChecklistExecutionDetailView,
    SmartSystemChecklistExecutionView,
    SmartSystemChecklistListView,
    SmartSystemChecklistUpdateView,
    SmartSystemContractActivateView,
    SmartSystemContractDetailView,
    SmartSystemContractGenerateBillingView,
    SmartSystemContractGeneratePreventivesView,
    SmartSystemContractListView,
    SmartSystemContractSuspendView,
    SmartSystemFailureDetailView,
    SmartSystemFailureListView,
    SmartSystemScheduleCalendarView,
    SmartSystemSchedulingDashboardView,
    SmartSystemPartDetailView,
    SmartSystemPartListView,
    SmartSystemPartCreateView,
    SmartSystemPartUpdateView,
    SmartSystemPartDeactivateView,
    SmartSystemQuoteApproveView,
    SmartSystemQuoteDetailView,
    SmartSystemQuoteListView,
    SmartSystemQuoteRejectView,
    SmartSystemQuoteSendView,
    SmartSystemPreventiveCalendarView,
    SmartSystemPreventiveDetailView,
    SmartSystemPreventiveListView,
    SmartSystemReportDownloadView,
    SmartSystemReportListView,
    SmartSystemReportPreviewView,
    SmartSystemPreventiveScheduleView,
    SmartSystemStockMovementView,
    SmartSystemTechnicianAgendaView,
    SmartSystemSiteCreateView,
    SmartSystemUnassignedVisitsView,
    SmartSystemWorkOrderChecklistSaveView,
    SmartSystemWorkOrderCreateView,
    SmartSystemWorkOrderPreventiveCreateView,
    SmartSystemWorkOrderDetailView,
    SmartSystemWorkOrderClientSignatureView,
    SmartSystemWorkOrderExecutionCompleteView,
    SmartSystemWorkOrderExecutionSaveView,
    SmartSystemWorkOrderExecutionStartView,
    SmartSystemWorkOrderTechnicianSignatureView,
    SmartSystemWorkOrderExecutionView,
    SmartSystemWorkOrderListView,
    SmartSystemWorkOrderTransitionView,
    SmartSystemWorkOrderWorkLogView,
    TechnicianChecklistListView,
    TechnicianBriefingDetailView,
    TechnicianExecutionClientSignatureView,
    TechnicianDashboardView,
    TechnicianExecutionCompleteView,
    TechnicianExecutionSaveView,
    TechnicianExecutionTechnicianSignatureView,
    TechnicianExecutionStartView,
    TechnicianOfflineBundleView,
    TechnicianCopilotContextView,
    TechnicianCopilotQueryView,
    TechnicianCopilotSuggestionsView,
    TechnicianCopilotSyncView,
    TechnicianOfflineSyncView,
    TechnicianExecutionView,
    TechnicianHistoryView,
    TechnicianLoginView,
    TechnicianLogoutView,
    TechnicianProfileView,
    TechnicianScheduleView,
    TechnicianServiceDetailView,
    TechnicianServiceListView,
    TechnicianServiceWorkerView,
    TechnicianSyncCenterView,
)

app_name = "admin-shell"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("dashboard/site-factory/", include("apps.smart_site_factory.urls")),
    path("ecossistema/", DashboardView.as_view(), name="dashboard-entry"),
    path("field/login/", TechnicianLoginView.as_view(), name="technician-app-login"),
    path("field/logout/", TechnicianLogoutView.as_view(), name="technician-app-logout"),
    path("field/sw.js", TechnicianServiceWorkerView.as_view(), name="technician-app-service-worker"),
    path("field/api/offline-bundle/", TechnicianOfflineBundleView.as_view(), name="technician-app-offline-bundle"),
    path("field/api/offline-sync/", TechnicianOfflineSyncView.as_view(), name="technician-app-offline-sync"),
    path("field/api/copilot/context/", TechnicianCopilotContextView.as_view(), name="technician-app-copilot-context"),
    path("field/api/copilot/query/", TechnicianCopilotQueryView.as_view(), name="technician-app-copilot-query"),
    path("field/api/copilot/suggestions/", TechnicianCopilotSuggestionsView.as_view(), name="technician-app-copilot-suggestions"),
    path("field/api/copilot/sync/", TechnicianCopilotSyncView.as_view(), name="technician-app-copilot-sync"),
    path("field/", TechnicianDashboardView.as_view(), name="technician-app-dashboard"),
    path("field/briefings/<uuid:briefing_id>/", TechnicianBriefingDetailView.as_view(), name="technician-app-briefing-detail"),
    path("field/schedule/", TechnicianScheduleView.as_view(), name="technician-app-schedule"),
    path("field/services/", TechnicianServiceListView.as_view(), name="technician-app-services"),
    path("field/services/<slug:order_code>/", TechnicianServiceDetailView.as_view(), name="technician-app-service-detail"),
    path("field/services/<slug:order_code>/execute/", TechnicianExecutionView.as_view(), name="technician-app-service-execution"),
    path("field/services/<slug:order_code>/start/", TechnicianExecutionStartView.as_view(), name="technician-app-service-start"),
    path("field/services/<slug:order_code>/save/", TechnicianExecutionSaveView.as_view(), name="technician-app-service-save"),
    path("field/services/<slug:order_code>/sign-technician/", TechnicianExecutionTechnicianSignatureView.as_view(), name="technician-app-service-sign-technician"),
    path("field/services/<slug:order_code>/sign-client/", TechnicianExecutionClientSignatureView.as_view(), name="technician-app-service-sign-client"),
    path("field/services/<slug:order_code>/complete/", TechnicianExecutionCompleteView.as_view(), name="technician-app-service-complete"),
    path("field/checklists/", TechnicianChecklistListView.as_view(), name="technician-app-checklists"),
    path("field/history/", TechnicianHistoryView.as_view(), name="technician-app-history"),
    path("field/sync/", TechnicianSyncCenterView.as_view(), name="technician-app-sync"),
    path("field/profile/", TechnicianProfileView.as_view(), name="technician-app-profile"),
    path("app/context/scope/", SetActiveContextView.as_view(), name="set-active-context"),
    path("portal/", ClientPortalDashboardView.as_view(), name="client-portal-dashboard"),
    path("portal/briefings/<uuid:briefing_id>/", ClientPortalBriefingDetailView.as_view(), name="client-portal-briefing-detail"),
    path("portal/copilot/", ClientPortalCopilotView.as_view(), name="client-portal-copilot"),
    path("portal/api/copilot/context/", ClientPortalCopilotContextView.as_view(), name="client-portal-copilot-context"),
    path("portal/api/copilot/query/", ClientPortalCopilotQueryView.as_view(), name="client-portal-copilot-query"),
    path("portal/api/copilot/suggestions/", ClientPortalCopilotSuggestionsView.as_view(), name="client-portal-copilot-suggestions"),
    path("portal/api/copilot/pending/", ClientPortalCopilotPendingItemsView.as_view(), name="client-portal-copilot-pending"),
    path("portal/assets/", ClientPortalAssetListView.as_view(), name="client-portal-assets"),
    path("portal/assets/<slug:asset_code>/", ClientPortalAssetDetailView.as_view(), name="client-portal-asset-detail"),
    path("portal/work-orders/", ClientPortalWorkOrderListView.as_view(), name="client-portal-work-orders"),
    path("portal/work-orders/<slug:order_code>/", ClientPortalWorkOrderDetailView.as_view(), name="client-portal-work-order-detail"),
    path("portal/preventives/", ClientPortalPreventiveListView.as_view(), name="client-portal-preventives"),
    path("portal/preventives/<uuid:public_id>/", ClientPortalPreventiveDetailView.as_view(), name="client-portal-preventive-detail"),
    path("portal/contracts/", ClientPortalContractListView.as_view(), name="client-portal-contracts"),
    path("portal/contracts/<slug:contract_number>/", ClientPortalContractDetailView.as_view(), name="client-portal-contract-detail"),
    path("portal/quotes/", ClientPortalQuoteListView.as_view(), name="client-portal-quotes"),
    path("portal/quotes/<slug:quote_number>/", ClientPortalQuoteDetailView.as_view(), name="client-portal-quote-detail"),
    path("portal/quotes/<slug:quote_number>/approve/", ClientPortalQuoteApproveView.as_view(), name="client-portal-quote-approve"),
    path("portal/quotes/<slug:quote_number>/reject/", ClientPortalQuoteRejectView.as_view(), name="client-portal-quote-reject"),
    path("portal/reports/", ClientPortalReportListView.as_view(), name="client-portal-reports"),
    path("portal/reports/<slug:report_type>/<slug:reference_code>/", ClientPortalReportPreviewView.as_view(), name="client-portal-report-preview"),
    path("portal/reports/<slug:report_type>/<slug:reference_code>/download/", ClientPortalReportDownloadView.as_view(), name="client-portal-report-download"),
    path("portal/requests/", ClientPortalRequestListView.as_view(), name="client-portal-requests"),
    path("portal/requests/new/", ClientPortalRequestCreateView.as_view(), name="client-portal-request-create"),
    path("portal/requests/<slug:protocol_number>/", ClientPortalRequestDetailView.as_view(), name="client-portal-request-detail"),
    path("portal/sites/", ClientPortalSitesView.as_view(), name="client-portal-sites"),
    path("portal/profile/", ClientPortalProfileView.as_view(), name="client-portal-profile"),
    path("dashboard/growth/marketplace-leads/", GrowthMarketplaceLeadListView.as_view(), name="growth-marketplace-leads"),
    path(
        "dashboard/growth/marketplace-leads/<int:lead_id>/create-proposal/",
        GrowthMarketplaceLeadCreateProposalView.as_view(),
        name="growth-marketplace-lead-create-proposal",
    ),
    path(
        "dashboard/growth/marketplace-leads/<int:lead_id>/",
        GrowthMarketplaceLeadDetailView.as_view(),
        name="growth-marketplace-lead-detail",
    ),
    path("dashboard/growth/leads/livia/", GrowthLiviaLeadListView.as_view(), name="growth-livia-leads"),
    path("dashboard/growth/leads/<int:lead_id>/", GrowthLeadDetailView.as_view(), name="growth-lead-detail"),
    path("dashboard/growth/leads/<int:lead_id>/create-proposal/", GrowthLeadCreateProposalView.as_view(), name="growth-lead-create-proposal"),
    path("dashboard/growth/leads/<int:lead_id>/<slug:action>/", GrowthLeadActionView.as_view(), name="growth-lead-action"),
    path(
        "dashboard/growth/proposals/approved/",
        GrowthApprovedProposalsListView.as_view(),
        name="growth-proposals-approved",
    ),
    path("dashboard/growth/proposals/<int:proposal_id>/", GrowthProposalDetailView.as_view(), name="growth-proposal-detail"),
    path(
        "dashboard/growth/proposals/<int:proposal_id>/mark-sent/",
        GrowthCommercialProposalActionView.as_view(action_name="mark-sent"),
        name="growth-proposal-mark-sent",
    ),
    path(
        "dashboard/growth/proposals/<int:proposal_id>/approve/",
        GrowthCommercialProposalActionView.as_view(action_name="approve"),
        name="growth-proposal-approve",
    ),
    path(
        "dashboard/growth/proposals/<int:proposal_id>/reject/",
        GrowthCommercialProposalActionView.as_view(action_name="reject"),
        name="growth-proposal-reject",
    ),
    path(
        "dashboard/growth/proposals/<int:proposal_id>/operational-forward/",
        GrowthCommercialProposalOperationalForwardView.as_view(),
        name="growth-proposal-operational-forward",
    ),
    path("dashboard/livia/", LiviaDashboardView.as_view(), name="livia-dashboard"),
    path("dashboard/livia/conversations/", LiviaConversationListView.as_view(), name="livia-conversations"),
    path("dashboard/livia/conversations/<int:conversation_id>/", LiviaConversationDetailView.as_view(), name="livia-conversation-detail"),
    path("dashboard/livia/leads/", LiviaLeadListView.as_view(), name="livia-leads"),
    path("dashboard/livia/leads/<int:lead_id>/", LiviaLeadDetailView.as_view(), name="livia-lead-detail"),
    path("dashboard/livia/leads/<int:lead_id>/<slug:action>/", LiviaLeadActionView.as_view(), name="livia-lead-action"),
    path("dashboard/livia/handoffs/", LiviaHandoffListView.as_view(), name="livia-handoffs"),
    path("dashboard/livia/knowledge/", LiviaKnowledgeListView.as_view(), name="livia-knowledge"),
    path("dashboard/livia/knowledge/new/", LiviaKnowledgeCreateView.as_view(), name="livia-knowledge-new"),
    path("dashboard/livia/knowledge/<int:knowledge_id>/edit/", LiviaKnowledgeUpdateView.as_view(), name="livia-knowledge-edit"),
    path("dashboard/media/images/", MediaAssetListView.as_view(), name="media-image-list"),
    path("dashboard/media/images/upload/", MediaAssetCreateView.as_view(), name="media-image-upload"),
    path(
        "dashboard/media/images/<int:pk>/deactivate/",
        MediaAssetDeactivateView.as_view(),
        name="media-image-deactivate",
    ),
    path("dashboard/media/images/<int:pk>/edit/", MediaAssetUpdateView.as_view(), name="media-image-edit"),
    path("dashboard/media/images/<int:pk>/", MediaAssetDetailView.as_view(), name="media-image-detail"),
    path("app/ai-agents/", AIAgentsDashboardView.as_view(), name="ai-agents-dashboard"),
    path("app/ai-agents/briefings/", AIBriefingListView.as_view(), name="ai-briefings"),
    path("app/ai-agents/briefings/generate/", AIBriefingGenerateView.as_view(), name="ai-briefing-generate"),
    path("app/ai-agents/briefings/<uuid:briefing_id>/", AIBriefingDetailView.as_view(), name="ai-briefing-detail"),
    path("app/ai-agents/copilot/", AIManagerCopilotView.as_view(), name="ai-manager-copilot"),
    path("app/ai-agents/recommendations/", AIAgentRecommendationsView.as_view(), name="ai-agents-recommendations"),
    path("app/ai-agents/maintenance-health/", AIAgentMaintenanceHealthView.as_view(), name="ai-agents-maintenance-health"),
    path("app/ai-agents/scheduling-health/", AIAgentSchedulingHealthView.as_view(), name="ai-agents-scheduling-health"),
    path("app/ai-agents/profitability-health/", AIAgentProfitabilityHealthView.as_view(), name="ai-agents-profitability-health"),
    path("app/ai-agents/marketplace-health/", AIAgentMarketplaceHealthView.as_view(), name="ai-agents-marketplace-health"),
    path("app/ai-agents/anomaly-health/", AIAgentAnomalyHealthView.as_view(), name="ai-agents-anomaly-health"),
    path("app/ai-agents/runs/", AIAgentRunsView.as_view(), name="ai-agents-runs"),
    path("app/ai-agents/decisions/", AIAgentActionProposalsView.as_view(), name="ai-decision-center"),
    path("app/ai-agents/simulations/", AISimulationCenterView.as_view(), name="ai-simulation-center"),
    path("app/ai-agents/optimization/", AIOptimizationCenterView.as_view(), name="ai-optimization-center"),
    path("app/ai-agents/policies/", AIPolicyStudioView.as_view(), name="ai-policy-studio"),
    path("app/ai-agents/experiments/", AIExperimentationCenterView.as_view(), name="ai-experimentation-center"),
    path("app/ai-agents/autonomy/", AIAutonomyCenterView.as_view(), name="ai-autonomy-center"),
    path("app/ai-agents/digital-twins/", AIDigitalTwinCenterView.as_view(), name="ai-digital-twin-center"),
    path("app/ai-agents/knowledge-graph/", AIKnowledgeGraphCenterView.as_view(), name="ai-knowledge-graph-center"),
    path("app/ai-agents/voiceops/", AIVoiceOpsCenterView.as_view(), name="ai-voiceops-center"),
    path("app/ai-agents/decisions/<uuid:decision_id>/approve/", AIDecisionApproveView.as_view(), name="ai-decision-approve"),
    path("app/ai-agents/decisions/<uuid:decision_id>/reject/", AIDecisionRejectView.as_view(), name="ai-decision-reject"),
    path("app/ai-agents/proposals/", AIAgentActionProposalsView.as_view(), name="ai-agents-proposals"),
    path("app/ai-agents/proposals/<uuid:proposal_id>/approve/", AIAgentProposalApproveView.as_view(), name="ai-agents-proposal-approve"),
    path("app/ai-agents/proposals/<uuid:proposal_id>/reject/", AIAgentProposalRejectView.as_view(), name="ai-agents-proposal-reject"),
    path("app/analytics/executive/refresh/", AnalyticsExecutiveRefreshView.as_view(), name="analytics-executive-refresh"),
    path("app/analytics/executive/", AnalyticsExecutiveDashboardView.as_view(), name="analytics-executive-dashboard"),
    path("app/analytics/war-room/", ExecutiveWarRoomView.as_view(), name="executive-war-room"),
    path("app/analytics/war-room/data/", ExecutiveWarRoomDataView.as_view(), name="executive-war-room-data"),
    path("app/analytics/war-room/stream/", ExecutiveWarRoomRealtimeStreamView.as_view(), name="executive-war-room-stream"),
    path("app/platform-admin/observability/", ObservabilityDashboardView.as_view(), name="observability-dashboard"),
    path("app/platform-admin/billing/", BillingAdminDashboardView.as_view(), name="billing-dashboard"),
    path("app/platform-admin/billing/plans/", BillingPlanListView.as_view(), name="billing-plans"),
    path("app/platform-admin/billing/contracts/", BillingContractListView.as_view(), name="billing-contracts"),
    path("app/platform-admin/billing/contracts/<slug:contract_code>/", BillingContractDetailView.as_view(), name="billing-contract-detail"),
    path("app/platform-admin/billing/contracts/<slug:contract_code>/suspend/", BillingContractSuspendView.as_view(), name="billing-contract-suspend"),
    path("app/platform-admin/billing/contracts/<slug:contract_code>/cancel/", BillingContractCancelView.as_view(), name="billing-contract-cancel"),
    path("app/platform-admin/billing/invoices/", BillingInvoiceListView.as_view(), name="billing-invoices"),
    path("app/platform-admin/billing/invoices/<slug:invoice_number>/mark-paid/", BillingInvoiceMarkPaidView.as_view(), name="billing-invoice-mark-paid"),
    path("app/platform-admin/billing/invoices/<slug:invoice_number>/cancel/", BillingInvoiceCancelView.as_view(), name="billing-invoice-cancel"),
    path("app/marketplace/technicians/", MarketplaceTechniciansDashboardView.as_view(), name="marketplace-technicians-dashboard"),
    path("app/marketplace/technicians/requests/", MarketplaceTechniciansRequestListView.as_view(), name="marketplace-technicians-requests"),
    path("app/marketplace/technicians/matching/", MarketplaceTechniciansMatchingListView.as_view(), name="marketplace-technicians-matching"),
    path("app/marketplace/technicians/offers/", MarketplaceTechniciansOfferListView.as_view(), name="marketplace-technicians-offers"),
    path("app/marketplace/technicians/profiles/", MarketplaceTechniciansTechnicianListView.as_view(), name="marketplace-technicians-technicians"),
    path("app/marketplace/technicians/profiles/<uuid:public_id>/", MarketplaceTechnicianDetailView.as_view(), name="marketplace-technicians-technician-detail"),
    path("app/marketplace/technicians/assignments/", MarketplaceTechniciansAssignmentListView.as_view(), name="marketplace-technicians-assignments"),
    path("app/marketplace/technicians/reviews/", MarketplaceTechniciansReviewListView.as_view(), name="marketplace-technicians-reviews"),
    path("app/smart-system/operations/", SmartSystemOperationsView.as_view(), name="smart-system-operations"),
    path("app/smart-system/reliability/", SmartSystemReliabilityView.as_view(), name="smart-system-reliability"),
    path("app/smart-system/assets/", SmartSystemAssetListView.as_view(), name="smart-system-assets"),
    path("app/smart-system/assets/<slug:asset_code>/", SmartSystemAssetDetailView.as_view(), name="smart-system-asset-detail"),
    path("app/smart-system/equipment-models/", SmartSystemEquipmentModelListView.as_view(), name="smart-system-equipment-models"),
    path("app/smart-system/equipment-models/new/", SmartSystemEquipmentModelCreateView.as_view(), name="smart-system-equipment-model-create"),
    path("app/smart-system/equipment-models/<slug:model_code>/", SmartSystemEquipmentModelDetailView.as_view(), name="smart-system-equipment-model-detail"),
    path("app/smart-system/equipment-models/<slug:model_code>/edit/", SmartSystemEquipmentModelUpdateView.as_view(), name="smart-system-equipment-model-update"),
    path("app/smart-system/customer-equipments/", SmartSystemCustomerEquipmentListView.as_view(), name="smart-system-customer-equipments"),
    path("app/smart-system/customer-equipments/new/", SmartSystemCustomerEquipmentCreateView.as_view(), name="smart-system-customer-equipment-create"),
    path("app/smart-system/customer-equipments/<slug:equipment_code>/", SmartSystemCustomerEquipmentDetailView.as_view(), name="smart-system-customer-equipment-detail"),
    path("app/smart-system/customer-equipments/<slug:equipment_code>/edit/", SmartSystemCustomerEquipmentUpdateView.as_view(), name="smart-system-customer-equipment-update"),
    path("app/smart-system/customers/", SmartSystemCustomerListView.as_view(), name="smart-system-customers"),
    path("app/smart-system/customers/new/", SmartSystemCustomerCreateView.as_view(), name="smart-system-customer-create"),
    path("app/smart-system/customers/<slug:customer_code>/", SmartSystemCustomerDetailView.as_view(), name="smart-system-customer-detail"),
    path("app/smart-system/customers/<slug:customer_code>/edit/", SmartSystemCustomerUpdateView.as_view(), name="smart-system-customer-update"),
    path("app/smart-system/sites/new/", SmartSystemSiteCreateView.as_view(), name="smart-system-site-create"),
    path("app/smart-system/scheduling/", SmartSystemSchedulingDashboardView.as_view(), name="smart-system-scheduling"),
    path("app/smart-system/scheduling/calendar/", SmartSystemScheduleCalendarView.as_view(), name="smart-system-scheduling-calendar"),
    path("app/smart-system/scheduling/technicians/<int:technician_id>/", SmartSystemTechnicianAgendaView.as_view(), name="smart-system-technician-agenda"),
    path("app/smart-system/scheduling/unassigned/", SmartSystemUnassignedVisitsView.as_view(), name="smart-system-unassigned-visits"),
    path("app/smart-system/parts/", SmartSystemPartListView.as_view(), name="smart-system-parts"),
    path("app/smart-system/contracts/", SmartSystemContractListView.as_view(), name="smart-system-contracts"),
    path("app/smart-system/contracts/<slug:contract_number>/", SmartSystemContractDetailView.as_view(), name="smart-system-contract-detail"),
    path("app/smart-system/contracts/<slug:contract_number>/activate/", SmartSystemContractActivateView.as_view(), name="smart-system-contract-activate"),
    path("app/smart-system/contracts/<slug:contract_number>/suspend/", SmartSystemContractSuspendView.as_view(), name="smart-system-contract-suspend"),
    path("app/smart-system/contracts/<slug:contract_number>/generate-preventives/", SmartSystemContractGeneratePreventivesView.as_view(), name="smart-system-contract-generate-preventives"),
    path("app/smart-system/contracts/<slug:contract_number>/generate-billing/", SmartSystemContractGenerateBillingView.as_view(), name="smart-system-contract-generate-billing"),
    path("app/smart-system/quotes/", SmartSystemQuoteListView.as_view(), name="smart-system-quotes"),
    path("app/smart-system/quotes/<slug:quote_number>/", SmartSystemQuoteDetailView.as_view(), name="smart-system-quote-detail"),
    path("app/smart-system/quotes/<slug:quote_number>/send/", SmartSystemQuoteSendView.as_view(), name="smart-system-quote-send"),
    path("app/smart-system/quotes/<slug:quote_number>/approve/", SmartSystemQuoteApproveView.as_view(), name="smart-system-quote-approve"),
    path("app/smart-system/quotes/<slug:quote_number>/reject/", SmartSystemQuoteRejectView.as_view(), name="smart-system-quote-reject"),
    path("app/smart-system/parts/movements/", SmartSystemStockMovementView.as_view(), name="smart-system-stock-movements"),
    path("app/smart-system/parts/new/", SmartSystemPartCreateView.as_view(), name="smart-system-part-create"),
    path("app/smart-system/parts/<slug:part_code>/edit/", SmartSystemPartUpdateView.as_view(), name="smart-system-part-update"),
    path("app/smart-system/parts/<slug:part_code>/deactivate/", SmartSystemPartDeactivateView.as_view(), name="smart-system-part-deactivate"),
    path("app/smart-system/parts/<slug:part_code>/", SmartSystemPartDetailView.as_view(), name="smart-system-part-detail"),
    path("app/smart-system/reports/", SmartSystemReportListView.as_view(), name="smart-system-reports"),
    path("app/smart-system/reports/<slug:report_type>/<slug:reference_code>/", SmartSystemReportPreviewView.as_view(), name="smart-system-report-preview"),
    path("app/smart-system/reports/<slug:report_type>/<slug:reference_code>/download/", SmartSystemReportDownloadView.as_view(), name="smart-system-report-download"),
    path("app/smart-system/checklists/", SmartSystemChecklistListView.as_view(), name="smart-system-checklists"),
    path("app/smart-system/checklists/new/", SmartSystemChecklistCreateView.as_view(), name="smart-system-checklist-create"),
    path("app/smart-system/checklists/<slug:checklist_code>/", SmartSystemChecklistDetailView.as_view(), name="smart-system-checklist-detail"),
    path("app/smart-system/checklists/<slug:checklist_code>/edit/", SmartSystemChecklistUpdateView.as_view(), name="smart-system-checklist-update"),
    path("app/smart-system/checklists/<slug:checklist_code>/deactivate/", SmartSystemChecklistDeactivateView.as_view(), name="smart-system-checklist-deactivate"),
    path("app/smart-system/checklists/<slug:checklist_code>/execute/", SmartSystemChecklistExecutionView.as_view(), name="smart-system-checklist-execution"),
    path("app/smart-system/checklists/<slug:checklist_code>/executions/<slug:execution_code>/", SmartSystemChecklistExecutionDetailView.as_view(), name="smart-system-checklist-execution-detail"),
    path("app/smart-system/failures/", SmartSystemFailureListView.as_view(), name="smart-system-failures"),
    path("app/smart-system/failures/<slug:failure_code>/", SmartSystemFailureDetailView.as_view(), name="smart-system-failure-detail"),
    path("app/smart-system/preventives/", SmartSystemPreventiveListView.as_view(), name="smart-system-preventives"),
    path("app/smart-system/preventives/schedule/", SmartSystemPreventiveScheduleView.as_view(), name="smart-system-preventives-schedule"),
    path("app/smart-system/preventives/calendar/", SmartSystemPreventiveCalendarView.as_view(), name="smart-system-preventives-calendar"),
    path("app/smart-system/preventives/<slug:plan_code>/", SmartSystemPreventiveDetailView.as_view(), name="smart-system-preventive-detail"),
    path("app/smart-system/work-orders/", SmartSystemWorkOrderListView.as_view(), name="smart-system-work-orders"),
    path("app/smart-system/work-orders/new/", SmartSystemWorkOrderCreateView.as_view(), name="smart-system-work-order-create"),
    path("app/smart-system/work-orders/new/preventive/", SmartSystemWorkOrderPreventiveCreateView.as_view(), name="smart-system-work-order-create-preventive"),
    path("app/smart-system/work-orders/<slug:order_code>/", SmartSystemWorkOrderDetailView.as_view(), name="smart-system-work-order-detail"),
    path("app/smart-system/work-orders/<slug:order_code>/execute/", SmartSystemWorkOrderExecutionView.as_view(), name="smart-system-work-order-execution"),
    path("app/smart-system/work-orders/<slug:order_code>/start-execution/", SmartSystemWorkOrderExecutionStartView.as_view(), name="smart-system-work-order-start-execution"),
    path("app/smart-system/work-orders/<slug:order_code>/save-progress/", SmartSystemWorkOrderExecutionSaveView.as_view(), name="smart-system-work-order-save-progress"),
    path("app/smart-system/work-orders/<slug:order_code>/capture-technician-signature/", SmartSystemWorkOrderTechnicianSignatureView.as_view(), name="smart-system-work-order-technician-signature"),
    path("app/smart-system/work-orders/<slug:order_code>/capture-client-signature/", SmartSystemWorkOrderClientSignatureView.as_view(), name="smart-system-work-order-client-signature"),
    path("app/smart-system/work-orders/<slug:order_code>/complete-execution/", SmartSystemWorkOrderExecutionCompleteView.as_view(), name="smart-system-work-order-complete-execution"),
    path("app/smart-system/work-orders/<slug:order_code>/transition/", SmartSystemWorkOrderTransitionView.as_view(), name="smart-system-work-order-transition"),
    path("app/smart-system/work-orders/<slug:order_code>/worklog/", SmartSystemWorkOrderWorkLogView.as_view(), name="smart-system-work-order-worklog"),
    path("app/smart-system/work-orders/<slug:order_code>/checklist-save/", SmartSystemWorkOrderChecklistSaveView.as_view(), name="smart-system-work-order-checklist-save"),
    path("app/<slug:module_slug>/", ModulePageView.as_view(), name="module-page"),
]
