from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def seed_default_policies(apps, schema_editor):
    DecisionPolicy = apps.get_model("ai_decision_engine", "DecisionPolicy")
    policies = [
        {
            "slug": "decision-create-work-order-proposal",
            "name": "Create Work Order Proposal",
            "description": "Ordens de servico derivadas de sinais dos agentes exigem aprovacao operacional.",
            "action_type": "create_work_order_proposal",
            "risk_level": "high",
            "autonomy_level": 1,
            "requires_human_approval": True,
            "enabled": True,
            "tenant_scope_mode": "site",
            "approver_role_slugs": ["maintenance-manager", "company-admin", "super-admin"],
            "config": {"auto_execute": True, "execution_mode": "after_approval"},
        },
        {
            "slug": "decision-create-preventive-review-task",
            "name": "Create Preventive Review Task",
            "description": "Revisoes preventivas permanecem aprovaveis por gestao de manutencao.",
            "action_type": "create_preventive_review_task",
            "risk_level": "medium",
            "autonomy_level": 1,
            "requires_human_approval": True,
            "enabled": True,
            "tenant_scope_mode": "site",
            "approver_role_slugs": ["maintenance-manager", "company-admin", "super-admin"],
            "config": {"auto_execute": True, "execution_mode": "after_approval"},
        },
        {
            "slug": "decision-mark-asset-attention",
            "name": "Mark Asset Attention",
            "description": "Marcacao de watchlist e segura para autoexecucao sob policy explicita.",
            "action_type": "mark_asset_attention",
            "risk_level": "low",
            "autonomy_level": 2,
            "requires_human_approval": False,
            "enabled": True,
            "tenant_scope_mode": "site",
            "approver_role_slugs": ["maintenance-manager", "company-admin", "super-admin"],
            "config": {"auto_execute": True, "execution_mode": "auto"},
        },
        {
            "slug": "decision-create-schedule-adjustment-proposal",
            "name": "Create Schedule Adjustment Proposal",
            "description": "Mudancas de agenda ficam aprovaveis por coordenacao operacional.",
            "action_type": "create_schedule_adjustment_proposal",
            "risk_level": "high",
            "autonomy_level": 1,
            "requires_human_approval": True,
            "enabled": True,
            "tenant_scope_mode": "site",
            "approver_role_slugs": ["coordinator", "company-admin", "super-admin"],
            "config": {"auto_execute": True, "execution_mode": "after_approval"},
        },
        {
            "slug": "decision-reorder-route-proposal",
            "name": "Reorder Route Proposal",
            "description": "Reordenacao de rota continua human-in-the-loop nesta rodada.",
            "action_type": "reorder_route_proposal",
            "risk_level": "medium",
            "autonomy_level": 1,
            "requires_human_approval": True,
            "enabled": True,
            "tenant_scope_mode": "site",
            "approver_role_slugs": ["coordinator", "company-admin", "super-admin"],
            "config": {"auto_execute": True, "execution_mode": "after_approval"},
        },
        {
            "slug": "decision-assign-marketplace-candidate-proposal",
            "name": "Assign Marketplace Candidate Proposal",
            "description": "Alocacoes de marketplace continuam aprovaveis por coordenacao.",
            "action_type": "assign_marketplace_candidate_proposal",
            "risk_level": "high",
            "autonomy_level": 1,
            "requires_human_approval": True,
            "enabled": True,
            "tenant_scope_mode": "company",
            "approver_role_slugs": ["coordinator", "company-admin", "super-admin"],
            "config": {"auto_execute": True, "execution_mode": "after_approval"},
        },
        {
            "slug": "decision-flag-contract-profitability-attention",
            "name": "Flag Contract Profitability Attention",
            "description": "Flags de rentabilidade sao registradas com seguranca; contratos criticos sobem para escalonamento.",
            "action_type": "flag_contract_profitability_attention",
            "risk_level": "medium",
            "autonomy_level": 2,
            "requires_human_approval": False,
            "enabled": True,
            "tenant_scope_mode": "company",
            "approver_role_slugs": ["commercial-manager", "company-admin", "super-admin"],
            "config": {"auto_execute": True, "execution_mode": "auto", "critical_requires_escalation": True},
        },
        {
            "slug": "decision-create-investigation-task",
            "name": "Create Investigation Task",
            "description": "Investigacoes internas podem ser materializadas automaticamente quando nao destrutivas.",
            "action_type": "create_investigation_task",
            "risk_level": "low",
            "autonomy_level": 2,
            "requires_human_approval": False,
            "enabled": True,
            "tenant_scope_mode": "site",
            "approver_role_slugs": ["maintenance-manager", "coordinator", "company-admin", "super-admin"],
            "config": {"auto_execute": True, "execution_mode": "auto"},
        },
        {
            "slug": "decision-escalate-operational-alert",
            "name": "Escalate Operational Alert",
            "description": "Escalonamentos permanecem auditados e com aprovacao quando houver impacto critico.",
            "action_type": "escalate_operational_alert",
            "risk_level": "medium",
            "autonomy_level": 1,
            "requires_human_approval": True,
            "enabled": True,
            "tenant_scope_mode": "site",
            "approver_role_slugs": ["coordinator", "maintenance-manager", "company-admin", "super-admin"],
            "config": {"auto_execute": True, "execution_mode": "after_approval"},
        },
    ]
    for item in policies:
        DecisionPolicy.objects.update_or_create(slug=item["slug"], defaults=item)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_agents_center", "0010_ai_briefings"),
        ("companies", "0002_sitemembership"),
        ("smart_system", "0009_maintenance_contracts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionPolicy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("action_type", models.CharField(db_index=True, max_length=80)),
                ("risk_level", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="medium", max_length=20)),
                ("autonomy_level", models.PositiveSmallIntegerField(choices=[(0, "Level 0 - Recommendation"), (1, "Level 1 - Human Approval"), (2, "Level 2 - Safe Auto Execution"), (3, "Level 3 - Expanded Autonomy")], default=1)),
                ("requires_human_approval", models.BooleanField(default=True)),
                ("enabled", models.BooleanField(default=True)),
                ("tenant_scope_mode", models.CharField(choices=[("global", "Global"), ("company", "Company"), ("site", "Site")], default="company", max_length=20)),
                ("approver_role_slugs", models.JSONField(blank=True, default=list)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "ai_decision_policies", "ordering": ["action_type", "name"]},
        ),
        migrations.CreateModel(
            name="AgentDecision",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("action_type", models.CharField(db_index=True, max_length=80)),
                ("normalized_action_type", models.CharField(db_index=True, max_length=80)),
                ("target_entity", models.CharField(blank=True, db_index=True, max_length=80)),
                ("target_entity_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("risk_level", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], db_index=True, default="medium", max_length=20)),
                ("autonomy_level", models.PositiveSmallIntegerField(default=1)),
                ("tenant_scope_mode", models.CharField(choices=[("global", "Global"), ("company", "Company"), ("site", "Site")], default="company", max_length=20)),
                ("requires_human_approval", models.BooleanField(default=True)),
                ("can_auto_execute", models.BooleanField(default=False)),
                ("rollback_required", models.BooleanField(default=False)),
                ("decision_status", models.CharField(choices=[("pending_policy", "Pending Policy"), ("awaiting_approval", "Awaiting Approval"), ("approved", "Approved"), ("rejected", "Rejected"), ("auto_approved", "Auto Approved"), ("auto_blocked", "Auto Blocked"), ("escalated", "Escalated"), ("executed", "Executed"), ("failed", "Failed")], db_index=True, default="pending_policy", max_length=30)),
                ("decision_reason", models.TextField(blank=True)),
                ("explainability_payload", models.JSONField(blank=True, default=dict)),
                ("execution_payload", models.JSONField(blank=True, default=dict)),
                ("escalation_target", models.CharField(blank=True, max_length=160)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent_action_proposal", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="decision", to="ai_agents_center.agentactionproposal")),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="agent_decisions", to="companies.company")),
                ("decided_by_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_decisions_made", to=settings.AUTH_USER_MODEL)),
                ("policy_applied", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decisions", to="ai_decision_engine.decisionpolicy")),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_decisions", to="smart_system.operationalsite")),
            ],
            options={"db_table": "ai_agent_decisions", "ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="agentdecision",
            index=models.Index(fields=["company", "decision_status"], name="ai_decision_company_status_idx"),
        ),
        migrations.AddIndex(
            model_name="agentdecision",
            index=models.Index(fields=["site", "decision_status"], name="ai_decision_site_status_idx"),
        ),
        migrations.AddIndex(
            model_name="agentdecision",
            index=models.Index(fields=["normalized_action_type", "risk_level"], name="ai_decision_action_risk_idx"),
        ),
        migrations.CreateModel(
            name="DecisionApproval",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("approval_status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("expired", "Expired")], db_index=True, default="pending", max_length=20)),
                ("requested_role_slugs", models.JSONField(blank=True, default=list)),
                ("comment", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approver_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decision_approvals", to=settings.AUTH_USER_MODEL)),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="ai_decision_engine.agentdecision")),
            ],
            options={"db_table": "ai_decision_approvals", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="DecisionExecution",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("execution_status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("rolled_back", "Rolled Back")], db_index=True, default="pending", max_length=20)),
                ("execution_summary", models.TextField(blank=True)),
                ("executed_by_mode", models.CharField(choices=[("auto", "Auto"), ("user", "User"), ("system", "System"), ("replay", "Replay")], default="system", max_length=20)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("rollback_supported", models.BooleanField(default=False)),
                ("rollback_status", models.CharField(choices=[("not_required", "Not Required"), ("available", "Available"), ("executed", "Executed"), ("failed", "Failed")], default="not_required", max_length=20)),
                ("rollback_reason", models.TextField(blank=True)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="executions", to="ai_decision_engine.agentdecision")),
                ("executed_by_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decision_executions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "ai_decision_executions", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="DecisionAuditTrail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=80)),
                ("actor_mode", models.CharField(choices=[("system", "System"), ("policy", "Policy"), ("user", "User"), ("handler", "Handler"), ("agent", "Agent")], default="system", max_length=20)),
                ("actor_label", models.CharField(blank=True, max_length=160)),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decision_audit_entries", to=settings.AUTH_USER_MODEL)),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_entries", to="ai_decision_engine.agentdecision")),
            ],
            options={"db_table": "ai_decision_audit_trail", "ordering": ["occurred_at", "id"]},
        ),
        migrations.RunPython(seed_default_policies, migrations.RunPython.noop),
    ]

