from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def seed_optimization_policies(apps, schema_editor):
    OptimizationPolicy = apps.get_model("ai_optimization_loop", "OptimizationPolicy")
    policies = [
        {
            "slug": "optimization-decision-policy-approval-adjustment",
            "name": "Decision Policy Approval Adjustment",
            "description": "Ajustes que elevam protecao de aprovacao em policies de decisao.",
            "target_type": "decision_policy",
            "proposal_type": "approval_requirement_adjustment",
            "risk_level": "high",
            "requires_human_approval": True,
            "auto_apply_on_approval": False,
            "approver_role_slugs": ["company-admin", "super-admin"],
            "enabled": True,
            "config": {"allowed_fields": ["requires_human_approval", "autonomy_level", "risk_level"]},
        },
        {
            "slug": "optimization-simulation-heuristic-adjustment",
            "name": "Simulation Heuristic Adjustment",
            "description": "Ajustes supervisionados na configuracao heuristica das simulacoes.",
            "target_type": "simulation_type",
            "proposal_type": "heuristic_config_adjustment",
            "risk_level": "medium",
            "requires_human_approval": True,
            "auto_apply_on_approval": False,
            "approver_role_slugs": ["maintenance-manager", "coordinator", "company-admin", "super-admin"],
            "enabled": True,
            "config": {"allowed_fields": ["heuristics_config", "policy_mode"]},
        },
        {
            "slug": "optimization-agent-execution-policy-ranking",
            "name": "Agent Execution Policy Ranking",
            "description": "Ajustes de volume e ranking de recomendacoes nos agentes.",
            "target_type": "agent_execution_policy",
            "proposal_type": "ranking_adjustment",
            "risk_level": "medium",
            "requires_human_approval": True,
            "auto_apply_on_approval": False,
            "approver_role_slugs": ["maintenance-manager", "company-admin", "super-admin"],
            "enabled": True,
            "config": {"allowed_fields": ["max_recommendations", "config"]},
        },
        {
            "slug": "optimization-copilot-behavior-adjustment",
            "name": "Copilot Behavior Adjustment",
            "description": "Ajustes de comportamento e ranking do copilot sob aprovacao supervisionada.",
            "target_type": "copilot_configuration",
            "proposal_type": "ranking_adjustment",
            "risk_level": "low",
            "requires_human_approval": True,
            "auto_apply_on_approval": False,
            "approver_role_slugs": ["company-admin", "super-admin"],
            "enabled": True,
            "config": {"allowed_fields": ["behavior_config"]},
        },
    ]
    for item in policies:
        OptimizationPolicy.objects.update_or_create(slug=item["slug"], defaults=item)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0002_sitemembership"),
        ("smart_system", "0009_maintenance_contracts"),
        ("access_control_center", "0002_access_audit_context_fields"),
        ("ai_agents_center", "0010_ai_briefings"),
        ("ai_decision_engine", "0001_initial"),
        ("ai_simulation_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackSignal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("source_type", models.CharField(choices=[("recommendation", "Recommendation"), ("decision", "Decision"), ("simulation", "Simulation"), ("copilot_message", "Copilot Message"), ("agent", "Agent")], db_index=True, max_length=30)),
                ("source_reference", models.CharField(db_index=True, max_length=120)),
                ("signal_type", models.CharField(choices=[("usefulness", "Usefulness"), ("quality", "Quality"), ("outcome", "Outcome"), ("confidence", "Confidence"), ("adoption", "Adoption"), ("implicit_operational", "Implicit Operational")], db_index=True, max_length=30)),
                ("score", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("comment", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="optimization_feedback_signals", to="companies.company")),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="optimization_feedback_signals", to="smart_system.operationalsite")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="optimization_feedback_signals", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "ai_optimization_feedback_signals", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OptimizationPolicy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("target_type", models.CharField(choices=[("agent_execution_policy", "Agent Execution Policy"), ("decision_policy", "Decision Policy"), ("simulation_type", "Simulation Type"), ("copilot_configuration", "Copilot Configuration")], db_index=True, max_length=40)),
                ("proposal_type", models.CharField(choices=[("weight_adjustment", "Weight Adjustment"), ("threshold_adjustment", "Threshold Adjustment"), ("policy_mode_adjustment", "Policy Mode Adjustment"), ("approval_requirement_adjustment", "Approval Requirement Adjustment"), ("ranking_adjustment", "Ranking Adjustment"), ("heuristic_config_adjustment", "Heuristic Config Adjustment")], db_index=True, max_length=40)),
                ("risk_level", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="medium", max_length=20)),
                ("requires_human_approval", models.BooleanField(default=True)),
                ("auto_apply_on_approval", models.BooleanField(default=False)),
                ("approver_role_slugs", models.JSONField(blank=True, default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "ai_optimization_policies", "ordering": ["target_type", "proposal_type", "slug"]},
        ),
        migrations.CreateModel(
            name="OptimizationProposal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("target_type", models.CharField(choices=[("agent_execution_policy", "Agent Execution Policy"), ("decision_policy", "Decision Policy"), ("simulation_type", "Simulation Type"), ("copilot_configuration", "Copilot Configuration")], db_index=True, max_length=40)),
                ("target_reference", models.CharField(db_index=True, max_length=120)),
                ("proposal_type", models.CharField(choices=[("weight_adjustment", "Weight Adjustment"), ("threshold_adjustment", "Threshold Adjustment"), ("policy_mode_adjustment", "Policy Mode Adjustment"), ("approval_requirement_adjustment", "Approval Requirement Adjustment"), ("ranking_adjustment", "Ranking Adjustment"), ("heuristic_config_adjustment", "Heuristic Config Adjustment")], db_index=True, max_length=40)),
                ("current_value", models.JSONField(blank=True, default=dict)),
                ("proposed_value", models.JSONField(blank=True, default=dict)),
                ("rationale", models.TextField()),
                ("evidence_summary", models.TextField(blank=True)),
                ("expected_impact_summary", models.TextField(blank=True)),
                ("risk_level", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], db_index=True, default="medium", max_length=20)),
                ("status", models.CharField(choices=[("pending_review", "Pending Review"), ("approved", "Approved"), ("rejected", "Rejected"), ("applied", "Applied"), ("failed", "Failed")], db_index=True, default="pending_review", max_length=20)),
                ("source_outcome_type", models.CharField(blank=True, db_index=True, max_length=40)),
                ("source_outcome_reference", models.CharField(blank=True, db_index=True, max_length=120)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("applied_by_mode", models.CharField(blank=True, choices=[("user", "User"), ("system", "System")], max_length=20)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="optimization_proposals_approved", to=settings.AUTH_USER_MODEL)),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="optimization_proposals", to="companies.company")),
                ("policy_applied", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="proposals", to="ai_optimization_loop.optimizationpolicy")),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="optimization_proposals", to="smart_system.operationalsite")),
            ],
            options={"db_table": "ai_optimization_proposals", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OptimizationAuditTrail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=80)),
                ("message", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="optimization_audit_entries", to=settings.AUTH_USER_MODEL)),
                ("proposal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="audit_entries", to="ai_optimization_loop.optimizationproposal")),
            ],
            options={"db_table": "ai_optimization_audit_trail", "ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="RecommendationOutcome",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("outcome_status", models.CharField(choices=[("pending", "Pending"), ("observed", "Observed"), ("dismissed", "Dismissed"), ("applied", "Applied")], db_index=True, default="pending", max_length=20)),
                ("expected_effect_summary", models.TextField(blank=True)),
                ("observed_effect_summary", models.TextField(blank=True)),
                ("effectiveness_score", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("effectiveness_level", models.CharField(choices=[("very_effective", "Very Effective"), ("effective", "Effective"), ("neutral", "Neutral"), ("weak", "Weak"), ("harmful", "Harmful")], db_index=True, default="neutral", max_length=20)),
                ("comparison_payload", models.JSONField(blank=True, default=dict)),
                ("measured_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="optimization_recommendation_outcomes", to="companies.company")),
                ("recommendation", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="optimization_outcome", to="ai_agents_center.agentrecommendation")),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="optimization_recommendation_outcomes", to="smart_system.operationalsite")),
            ],
            options={"db_table": "ai_optimization_recommendation_outcomes", "ordering": ["-measured_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="DecisionOutcome",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("execution_status", models.CharField(blank=True, db_index=True, max_length=20)),
                ("result_status", models.CharField(choices=[("pending", "Pending"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("reverted", "Reverted"), ("partial", "Partial")], db_index=True, default="pending", max_length=20)),
                ("expected_result", models.JSONField(blank=True, default=dict)),
                ("actual_result", models.JSONField(blank=True, default=dict)),
                ("effectiveness_score", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("effectiveness_level", models.CharField(choices=[("very_effective", "Very Effective"), ("effective", "Effective"), ("neutral", "Neutral"), ("weak", "Weak"), ("harmful", "Harmful")], db_index=True, default="neutral", max_length=20)),
                ("evaluation_summary", models.TextField(blank=True)),
                ("measured_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="optimization_decision_outcomes", to="companies.company")),
                ("decision", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="optimization_outcome", to="ai_decision_engine.agentdecision")),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="optimization_decision_outcomes", to="smart_system.operationalsite")),
            ],
            options={"db_table": "ai_optimization_decision_outcomes", "ordering": ["-measured_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="SimulationOutcome",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("result_status", models.CharField(choices=[("pending", "Pending"), ("observed", "Observed"), ("not_executed", "Not Executed"), ("diverged", "Diverged")], db_index=True, default="pending", max_length=20)),
                ("expected_result", models.JSONField(blank=True, default=dict)),
                ("actual_result", models.JSONField(blank=True, default=dict)),
                ("effectiveness_score", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("effectiveness_level", models.CharField(choices=[("very_effective", "Very Effective"), ("effective", "Effective"), ("neutral", "Neutral"), ("weak", "Weak"), ("harmful", "Harmful")], db_index=True, default="neutral", max_length=20)),
                ("evaluation_summary", models.TextField(blank=True)),
                ("measured_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="optimization_simulation_outcomes", to="companies.company")),
                ("simulation_run", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="optimization_outcome", to="ai_simulation_engine.simulationrun")),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="optimization_simulation_outcomes", to="smart_system.operationalsite")),
            ],
            options={"db_table": "ai_optimization_simulation_outcomes", "ordering": ["-measured_at", "-created_at"]},
        ),
        migrations.AddIndex(
            model_name="optimizationproposal",
            index=models.Index(fields=["company", "status"], name="ai_opt_proposal_company_status_idx"),
        ),
        migrations.AddIndex(
            model_name="optimizationproposal",
            index=models.Index(fields=["target_type", "proposal_type"], name="ai_opt_proposal_target_type_idx"),
        ),
        migrations.RunPython(seed_optimization_policies, migrations.RunPython.noop),
    ]
