import django.db.models.deletion
import django.utils.timezone
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("smart_system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRegion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region_type", models.CharField(choices=[("city", "City"), ("state", "State"), ("metropolitan", "Metropolitan"), ("custom", "Custom")], default="city", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "marketplace_service_regions", "ordering": ["state", "city", "name"]},
        ),
        migrations.AddConstraint(
            model_name="serviceregion",
            constraint=models.UniqueConstraint(fields=("name", "state", "city", "region_type"), name="uniq_marketplace_service_region"),
        ),
        migrations.CreateModel(
            name="TechnicianProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("display_name", models.CharField(max_length=180)),
                ("document_number", models.CharField(blank=True, max_length=40)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("bio", models.TextField(blank=True)),
                ("profile_type", models.CharField(choices=[("independent", "Independent"), ("company", "Company"), ("internal", "Internal")], default="independent", max_length=20)),
                ("experience_years", models.PositiveIntegerField(blank=True, null=True)),
                ("verification_status", models.CharField(choices=[("pending", "Pending"), ("under_review", "Under Review"), ("approved", "Approved"), ("suspended", "Suspended"), ("blocked", "Blocked")], default="pending", max_length=20)),
                ("marketplace_status", models.CharField(choices=[("pending", "Pending"), ("available", "Available"), ("busy", "Busy"), ("offline", "Offline"), ("suspended", "Suspended")], default="pending", max_length=20)),
                ("trust_case_reference", models.CharField(blank=True, max_length=100)),
                ("rating_average", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ("completed_jobs_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="technician_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "marketplace_technician_profiles", "ordering": ["display_name"]},
        ),
        migrations.CreateModel(
            name="TechnicianSkill",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "marketplace_technician_skills", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="TechnicianPortfolioItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("media_file", models.FileField(blank=True, null=True, upload_to="marketplace_technicians/portfolio/")),
                ("media_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("ordering", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("technician_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_items", to="marketplace_technicians.technicianprofile")),
            ],
            options={"db_table": "marketplace_technician_portfolio_items", "ordering": ["ordering", "-created_at"]},
        ),
        migrations.CreateModel(
            name="TechnicianServiceRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("service_type", models.CharField(choices=[("maintenance", "Maintenance"), ("installation", "Installation"), ("inspection", "Inspection"), ("emergency", "Emergency")], max_length=20)),
                ("priority", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")], default="medium", max_length=20)),
                ("requested_date", models.DateTimeField(blank=True, null=True)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("address_line", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("open", "Open"), ("matching", "Matching"), ("assigned", "Assigned"), ("in_progress", "In Progress"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="open", max_length=20)),
                ("origin", models.CharField(choices=[("direct", "Marketplace Direct"), ("smart_system", "Smart System"), ("manual", "Manual")], default="direct", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("related_asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="technician_requests", to="smart_system.asset")),
                ("related_client", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="technician_requests", to="smart_system.maintenanceclient")),
                ("related_service_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="technician_requests", to="smart_system.serviceorder")),
                ("related_site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="technician_requests", to="smart_system.operationalsite")),
                ("requester_company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="technician_service_requests", to="companies.company")),
                ("requester_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="technician_service_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "marketplace_technician_service_requests", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TechnicianAvailability",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("weekday", models.PositiveSmallIntegerField(choices=[(1, "Monday"), (2, "Tuesday"), (3, "Wednesday"), (4, "Thursday"), (5, "Friday"), (6, "Saturday"), (7, "Sunday")])),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("technician_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="availabilities", to="marketplace_technicians.technicianprofile")),
            ],
            options={"db_table": "marketplace_technician_availabilities", "ordering": ["technician_profile__display_name", "weekday", "start_time"]},
        ),
        migrations.CreateModel(
            name="TechnicianSkillAssignment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("proficiency_level", models.CharField(choices=[("basic", "Basic"), ("intermediate", "Intermediate"), ("advanced", "Advanced"), ("specialist", "Specialist")], default="intermediate", max_length=20)),
                ("years_experience", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("skill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="marketplace_technicians.technicianskill")),
                ("technician_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skill_assignments", to="marketplace_technicians.technicianprofile")),
            ],
            options={"db_table": "marketplace_technician_skill_assignments", "ordering": ["technician_profile__display_name", "skill__name"]},
        ),
        migrations.AddConstraint(
            model_name="technicianskillassignment",
            constraint=models.UniqueConstraint(fields=("technician_profile", "skill"), name="uniq_marketplace_technician_skill"),
        ),
        migrations.CreateModel(
            name="TechnicianServiceRegion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("coverage_type", models.CharField(choices=[("local", "Local"), ("travel", "Travel"), ("remote", "Remote")], default="local", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_region", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="technicians", to="marketplace_technicians.serviceregion")),
                ("technician_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="service_regions", to="marketplace_technicians.technicianprofile")),
            ],
            options={"db_table": "marketplace_technician_service_regions", "ordering": ["technician_profile__display_name"]},
        ),
        migrations.AddConstraint(
            model_name="technicianserviceregion",
            constraint=models.UniqueConstraint(fields=("technician_profile", "service_region"), name="uniq_marketplace_technician_region"),
        ),
        migrations.CreateModel(
            name="TechnicianMatchingRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("match_score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("match_reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("suggested", "Suggested"), ("notified", "Notified"), ("accepted", "Accepted"), ("declined", "Declined"), ("expired", "Expired")], default="suggested", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("technician_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matching_records", to="marketplace_technicians.technicianprofile")),
                ("technician_service_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matching_records", to="marketplace_technicians.technicianservicerequest")),
            ],
            options={"db_table": "marketplace_technician_matching_records", "ordering": ["-match_score", "-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="technicianmatchingrecord",
            constraint=models.UniqueConstraint(fields=("technician_service_request", "technician_profile"), name="uniq_marketplace_matching_record"),
        ),
        migrations.CreateModel(
            name="TechnicianAssignment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("assignment_status", models.CharField(choices=[("assigned", "Assigned"), ("accepted", "Accepted"), ("declined", "Declined"), ("in_progress", "In Progress"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="assigned", max_length=20)),
                ("assigned_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("technician_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="marketplace_technicians.technicianprofile")),
                ("technician_service_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="marketplace_technicians.technicianservicerequest")),
            ],
            options={"db_table": "marketplace_technician_assignments", "ordering": ["-assigned_at"]},
        ),
        migrations.AddConstraint(
            model_name="technicianassignment",
            constraint=models.UniqueConstraint(fields=("technician_service_request", "technician_profile"), name="uniq_marketplace_assignment"),
        ),
        migrations.CreateModel(
            name="TechnicianWorkReport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("summary", models.CharField(max_length=255)),
                ("execution_notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("labor_minutes", models.PositiveIntegerField(default=0)),
                ("materials_used", models.JSONField(blank=True, default=list)),
                ("next_recommendation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("technician_assignment", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="work_report", to="marketplace_technicians.technicianassignment")),
            ],
            options={"db_table": "marketplace_technician_work_reports", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TechnicianReview",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("published", "Published"), ("pending", "Pending"), ("flagged", "Flagged")], default="published", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="marketplace_technicians.technicianassignment")),
                ("reviewer_company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="technician_reviews", to="companies.company")),
                ("reviewer_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="technician_reviews", to=settings.AUTH_USER_MODEL)),
                ("technician_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="marketplace_technicians.technicianprofile")),
            ],
            options={"db_table": "marketplace_technician_reviews", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TechnicianCompensationRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("platform_fee", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("paid", "Paid"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("technician_assignment", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="compensation_record", to="marketplace_technicians.technicianassignment")),
            ],
            options={"db_table": "marketplace_technician_compensations", "ordering": ["-created_at"]},
        ),
    ]
