import django.db.models.deletion
import django.utils.timezone
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("smart_system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticalProvider",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("display_name", models.CharField(max_length=180)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("document_number", models.CharField(blank=True, max_length=40)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("provider_type", models.CharField(choices=[("laboratory", "Laboratory"), ("consultant", "Consultant"), ("engineering_firm", "Engineering Firm"), ("specialist", "Specialist")], default="specialist", max_length=20)),
                ("verification_status", models.CharField(choices=[("pending", "Pending"), ("under_review", "Under Review"), ("approved", "Approved"), ("suspended", "Suspended"), ("blocked", "Blocked")], default="pending", max_length=20)),
                ("marketplace_status", models.CharField(choices=[("pending", "Pending"), ("available", "Available"), ("busy", "Busy"), ("offline", "Offline"), ("suspended", "Suspended")], default="pending", max_length=20)),
                ("trust_case_reference", models.CharField(blank=True, max_length=100)),
                ("knowledge_profile_reference", models.CharField(blank=True, max_length=100)),
                ("rating_average", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ("completed_jobs_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytical_providers", to="companies.company")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytical_providers", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "marketplace_analytical_providers", "ordering": ["display_name"]},
        ),
        migrations.CreateModel(
            name="AnalyticalServiceCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "marketplace_analytical_service_categories", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="AnalyticalService",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("service_type", models.CharField(choices=[("analysis", "Analysis"), ("diagnostic", "Diagnostic"), ("inspection", "Inspection"), ("consulting", "Consulting"), ("audit", "Audit")], max_length=20)),
                ("delivery_type", models.CharField(choices=[("remote", "Remote"), ("on_site", "On Site"), ("hybrid", "Hybrid")], default="remote", max_length=20)),
                ("estimated_turnaround_days", models.PositiveIntegerField(default=5)),
                ("price_model", models.CharField(choices=[("fixed", "Fixed"), ("quote", "Quote"), ("hourly", "Hourly"), ("package", "Package")], default="quote", max_length=20)),
                ("base_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("currency", models.CharField(default="BRL", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="services", to="marketplace_analytical.analyticalservicecategory")),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="services", to="marketplace_analytical.analyticalprovider")),
            ],
            options={"db_table": "marketplace_analytical_services", "ordering": ["provider__display_name", "title"]},
        ),
        migrations.CreateModel(
            name="AnalyticalRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("priority", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")], default="medium", max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="Brazil", max_length=100)),
                ("requested_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("open", "Open"), ("matching", "Matching"), ("assigned", "Assigned"), ("in_progress", "In Progress"), ("delivered", "Delivered"), ("cancelled", "Cancelled")], default="open", max_length=20)),
                ("origin", models.CharField(choices=[("direct", "Marketplace Direct"), ("smart_system", "Smart System"), ("external", "External Client")], default="direct", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requests", to="marketplace_analytical.analyticalservicecategory")),
                ("related_asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytical_requests", to="smart_system.asset")),
                ("related_service_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytical_requests", to="smart_system.serviceorder")),
                ("related_site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytical_requests", to="smart_system.operationalsite")),
                ("requester_company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytical_requests", to="companies.company")),
                ("requester_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytical_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "marketplace_analytical_requests", "ordering": ["-requested_date"]},
        ),
        migrations.CreateModel(
            name="AnalyticalServiceCapability",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("capability_name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analytical_service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="capabilities", to="marketplace_analytical.analyticalservice")),
            ],
            options={"db_table": "marketplace_analytical_service_capabilities", "ordering": ["analytical_service__title", "capability_name"]},
        ),
        migrations.CreateModel(
            name="AnalyticalServiceRegion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("region_name", models.CharField(max_length=120)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Brazil", max_length=100)),
                ("coverage_type", models.CharField(choices=[("local", "Local"), ("regional", "Regional"), ("national", "National"), ("international", "International")], default="local", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analytical_service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="service_regions", to="marketplace_analytical.analyticalservice")),
            ],
            options={"db_table": "marketplace_analytical_service_regions", "ordering": ["country", "state", "region_name"]},
        ),
        migrations.CreateModel(
            name="AnalyticalMatchingRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("match_score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("match_reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("suggested", "Suggested"), ("notified", "Notified"), ("accepted", "Accepted"), ("declined", "Declined"), ("expired", "Expired")], default="suggested", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analytical_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matching_records", to="marketplace_analytical.analyticalrequest")),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="matching_records", to="marketplace_analytical.analyticalprovider")),
            ],
            options={"db_table": "marketplace_analytical_matching_records", "ordering": ["-match_score", "-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="analyticalmatchingrecord",
            constraint=models.UniqueConstraint(fields=("analytical_request", "provider"), name="uniq_marketplace_analytical_matching"),
        ),
        migrations.CreateModel(
            name="AnalyticalAssignment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("status", models.CharField(choices=[("assigned", "Assigned"), ("accepted", "Accepted"), ("declined", "Declined"), ("in_progress", "In Progress"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="assigned", max_length=20)),
                ("assigned_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analytical_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="marketplace_analytical.analyticalrequest")),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="marketplace_analytical.analyticalprovider")),
            ],
            options={"db_table": "marketplace_analytical_assignments", "ordering": ["-assigned_at"]},
        ),
        migrations.AddConstraint(
            model_name="analyticalassignment",
            constraint=models.UniqueConstraint(fields=("analytical_request", "provider"), name="uniq_marketplace_analytical_assignment"),
        ),
        migrations.CreateModel(
            name="AnalyticalReport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("summary", models.TextField(blank=True)),
                ("report_file", models.FileField(upload_to="marketplace_analytical/reports/")),
                ("technical_conclusion", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analytical_assignment", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="report", to="marketplace_analytical.analyticalassignment")),
            ],
            options={"db_table": "marketplace_analytical_reports", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AnalyticalReview",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analytical_assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="marketplace_analytical.analyticalassignment")),
                ("reviewer_company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytical_reviews", to="companies.company")),
                ("reviewer_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytical_reviews", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "marketplace_analytical_reviews", "ordering": ["-created_at"]},
        ),
    ]
