from django.urls import path
from django.views.generic import RedirectView

from . import views


app_name = "institutional"


urlpatterns = [
    path("", views.home, name="home"),
    path("sobre/", views.about, name="about"),
    path("solucoes/", views.services, name="services"),
    path(
        "servicos/",
        RedirectView.as_view(pattern_name="institutional:services", permanent=True),
    ),
    path("servicos/detalhes/", views.service_details, name="service_details"),
    path("servicos/marketing-digital-sites-conteudo/", views.service_marketing_digital, name="service_marketing_digital"),
    path("servicos/automacao-industrial-clps/", views.service_automacao_industrial_clps, name="service_automacao_industrial_clps"),
    path("servicos/inteligencia-artificial-aplicada/", views.service_inteligencia_artificial, name="service_inteligencia_artificial"),
    path("servicos/robotica-integracao-sistemas/", views.service_robotica_integracao, name="service_robotica_integracao"),
    path("servicos/manutencao-tpm-confiabilidade/", views.service_manutencao_tpm_confiabilidade, name="service_manutencao_tpm_confiabilidade"),
    path("servicos/diagnostico-ia-dados-automacao/", views.service_diagnostico_ia_dados_automacao, name="service_diagnostico_ia_dados_automacao"),
    path("blog/", views.blog, name="blog"),
    path("blog/pagina/2/", views.blog_page_2, name="blog_page_2"),
    path("blog/detalhes/", views.blog_details, name="blog_details"),
    # Static individual blog posts focused on industrial automation.
    path("blog/retrofit-maquina-industrial/", views.blog_retrofit_maquina_industrial, name="blog_retrofit_maquina_industrial"),
    path("blog/organizar-sinais-dados-antes-automatizar/", views.blog_organizar_sinais_dados_antes_automatizar, name="blog_organizar_sinais_dados_antes_automatizar"),
    path("blog/manutencao-tpm-confiabilidade-sistemas-automatizados/", views.blog_manutencao_tpm_confiabilidade_sistemas_automatizados, name="blog_manutencao_tpm_confiabilidade_sistemas_automatizados"),
    path("blog/clp-ihm-inversor-falhas-maquina/", views.blog_clp_ihm_inversor_falhas_maquina, name="blog_clp_ihm_inversor_falhas_maquina"),
    path("blog/supervisorio-industrial-dados-tempo-real/", views.blog_supervisorio_industrial_dados_tempo_real, name="blog_supervisorio_industrial_dados_tempo_real"),
    path("blog/automacao-industrial-conectada-manutencao-gestao/", views.blog_automacao_industrial_conectada_manutencao_gestao, name="blog_automacao_industrial_conectada_manutencao_gestao"),
    path("blog/paineis-eletricos-organizacao-seguranca-manutenibilidade/", views.blog_paineis_eletricos_organizacao_seguranca_manutenibilidade, name="blog_paineis_eletricos_organizacao_seguranca_manutenibilidade"),
    path("blog/dados-industriais-confiabilidade-reduzir-paradas/", views.blog_dados_industriais_confiabilidade_reduzir_paradas, name="blog_dados_industriais_confiabilidade_reduzir_paradas"),
    path("blog/ia-pequenas-empresas/", RedirectView.as_view(pattern_name="institutional:blog_retrofit_maquina_industrial", permanent=False), name="blog_ia_pequenas_empresas"),
    path("blog/organizar-dados-antes-automatizar/", RedirectView.as_view(pattern_name="institutional:blog_organizar_sinais_dados_antes_automatizar", permanent=False), name="blog_organizar_dados_antes_automatizar"),
    path("blog/manutencao-tpm-confiabilidade-digital/", RedirectView.as_view(pattern_name="institutional:blog_manutencao_tpm_confiabilidade_sistemas_automatizados", permanent=False), name="blog_manutencao_tpm_confiabilidade_digital"),
    path("blog/cybersecurity-pequenas-empresas/", RedirectView.as_view(pattern_name="institutional:blog_clp_ihm_inversor_falhas_maquina", permanent=False), name="blog_cybersecurity_pequenas_empresas"),
    path("blog/sistemas-web-operacao-moderna/", RedirectView.as_view(pattern_name="institutional:blog_supervisorio_industrial_dados_tempo_real", permanent=False), name="blog_sistemas_web_operacao_moderna"),
    path("blog/automacao-industrial-conectada-gestao/", RedirectView.as_view(pattern_name="institutional:blog_automacao_industrial_conectada_manutencao_gestao", permanent=False), name="blog_automacao_industrial_conectada_gestao"),
    path("blog/marketing-digital-tecnologia-processo/", RedirectView.as_view(pattern_name="institutional:blog_paineis_eletricos_organizacao_seguranca_manutenibilidade", permanent=False), name="blog_marketing_digital_tecnologia_processo"),
    path("blog/smart360-operacao-inteligente/", RedirectView.as_view(pattern_name="institutional:blog_dados_industriais_confiabilidade_reduzir_paradas", permanent=False), name="blog_smart360_operacao_inteligente"),
    path("smart360/", views.smart360, name="smart360"),
    path("contato/", views.contact, name="contact"),
    path("equipe/", views.team, name="team"),
    path("projetos/", views.projects, name="projects"),
    path("projetos/pagina/2/", views.projects_page_2, name="projects_page_2"),
    path("projetos/pagina/3/", views.projects_page_3, name="projects_page_3"),
    path("projetos/supervisao-dados-industriais/", views.supervisao_dados_industriais, name="supervisao_dados_industriais"),
    path("projetos/diagnostico-industrial-engenharia-solucao/", views.diagnostico_industrial_engenharia_solucao, name="diagnostico_industrial_engenharia_solucao"),
    path("projetos/automacao-industrial-clps-ihms/", views.automacao_industrial_clps_ihms, name="automacao_industrial_clps_ihms"),
    path("projetos/manutencao-retrofit-confiabilidade/", views.manutencao_retrofit_confiabilidade, name="manutencao_retrofit_confiabilidade"),
    path("projetos/inversores-eficiencia-energetica/", views.inversores_eficiencia_energetica, name="inversores_eficiencia_energetica"),
    path("projetos/servoacionamentos-motion-control/", views.servoacionamentos_motion_control, name="servoacionamentos_motion_control"),
    path("projetos/supervisorio-scada-dados-industriais/", views.supervisorio_scada_dados_industriais, name="supervisorio_scada_dados_industriais"),
    path("projetos/robotica-celulas-automatizadas/", views.robotica_celulas_automatizadas, name="robotica_celulas_automatizadas"),
    path("projetos/gerenciamento-energia-utilidades/", views.gerenciamento_energia_utilidades, name="gerenciamento_energia_utilidades"),
    path("projetos/paineis-eletricos-baixa-tensao/", views.paineis_eletricos_baixa_tensao, name="paineis_eletricos_baixa_tensao"),
    path("projetos/integracao-chao-fabrica-dados-industriais/", views.integracao_chao_fabrica_dados_industriais, name="integracao_chao_fabrica_dados_industriais"),
    path("projetos/seguranca-maquinas-continuidade-operacional/", views.seguranca_maquinas_continuidade_operacional, name="seguranca_maquinas_continuidade_operacional"),
    path("projetos/smart360/", RedirectView.as_view(pattern_name="institutional:supervisao_dados_industriais", permanent=False), name="project_smart360"),
    path("projetos/diagnostico-ia-dados-automacao/", RedirectView.as_view(pattern_name="institutional:diagnostico_industrial_engenharia_solucao", permanent=False), name="project_diagnostico_ia_dados_automacao"),
    path("projetos/automacao-industrial-clps/", RedirectView.as_view(pattern_name="institutional:automacao_industrial_clps_ihms", permanent=False), name="project_automacao_industrial_clps"),
    path("projetos/manutencao-confiabilidade/", RedirectView.as_view(pattern_name="institutional:manutencao_retrofit_confiabilidade", permanent=False), name="project_manutencao_confiabilidade"),
    path("projetos/cybersecurity-empresas/", RedirectView.as_view(pattern_name="institutional:inversores_eficiencia_energetica", permanent=False), name="project_cybersecurity_empresas"),
    path("projetos/sites-marketing-conteudo/", RedirectView.as_view(pattern_name="institutional:servoacionamentos_motion_control", permanent=False), name="project_sites_marketing_conteudo"),
    path("projetos/sistemas-web-django-python/", RedirectView.as_view(pattern_name="institutional:supervisorio_scada_dados_industriais", permanent=False), name="project_sistemas_web_django_python"),
    path("projetos/ia-atendimento-operacao/", RedirectView.as_view(pattern_name="institutional:robotica_celulas_automatizadas", permanent=False), name="project_ia_atendimento_operacao"),
    path("projetos/dashboards-indicadores-operacionais/", RedirectView.as_view(pattern_name="institutional:gerenciamento_energia_utilidades", permanent=False), name="project_dashboards_indicadores_operacionais"),
    path("projetos/gestao-os-ativos/", RedirectView.as_view(pattern_name="institutional:paineis_eletricos_baixa_tensao", permanent=False), name="project_gestao_os_ativos"),
    path("projetos/integracao-dados-sistemas/", RedirectView.as_view(pattern_name="institutional:integracao_chao_fabrica_dados_industriais", permanent=False), name="project_integracao_dados_sistemas"),
    path("projetos/seguranca-backup-continuidade/", RedirectView.as_view(pattern_name="institutional:seguranca_maquinas_continuidade_operacional", permanent=False), name="project_seguranca_backup_continuidade"),
    path("projetos/detalhes/", views.project_details, name="project_details"),
    path("faq/", views.faq, name="faq"),
    # Aliases curtos para manter compatibilidade com o novo plano de URLs publicas.
    path("about/", views.about, name="about_alias"),
    path(
        "services/",
        RedirectView.as_view(pattern_name="institutional:services", permanent=True),
        name="services_alias",
    ),
    path("contact/", views.contact, name="contact_alias"),
    path("service-details/", views.service_details, name="service_details_alias"),
    path("team/", views.team, name="team_alias"),
    path("projects/", views.projects, name="projects_alias"),
    path("project-details/", views.project_details, name="project_details_alias"),
    path("blog-details/", views.blog_details, name="blog_details_alias"),
    path(
        "automacao-industrial/",
        views.solution_detail,
        {"slug": "automacao-industrial"},
        name="automacao_industrial",
    ),
    path(
        "ar-condicionado/",
        views.solution_detail,
        {"slug": "ar-condicionado"},
        name="ar_condicionado",
    ),
    path(
        "seguranca-da-informacao/",
        views.solution_detail,
        {"slug": "seguranca-da-informacao"},
        name="seguranca_da_informacao",
    ),
    path(
        "sites-sistemas-marketing/",
        views.solution_detail,
        {"slug": "sites-sistemas-marketing"},
        name="sites_sistemas_marketing",
    ),
]
