"""Static content for Xyron Robotics institutional detail pages."""

XYRON_ROBOTS = [
    {
        "slug": "liro-littlebot",
        "name": "LIRO / LittleBot",
        "short_name": "LIRO / LittleBot",
        "subtitle": "Robô educacional com IA para experiências pedagógicas, projetos maker e interação humano-robô com mediação humana.",
        "image": "institutional/eitech/img/all-images/blog/banner-little.png",
        "secondary_images": [
            "institutional/eitech/img/elements/liro-robo-educacional.png",
            "institutional/eitech/img/all-images/team/littlebot.webp",
        ],
        "intro": [
            "O LIRO / LittleBot é um robô educacional da Xyron Robotics pensado para aproximar estudantes, educadores e instituições de experiências práticas com robótica, inteligência artificial e interação humano-robô.",
            "Ele não substitui o professor. Ele amplia a mediação pedagógica, cria pontos de interação e ajuda a transformar conceitos abstratos de tecnologia em experiências visíveis, conversáveis e memoráveis.",
        ],
        "benefits": [
            "Robótica educacional para escolas e projetos maker",
            "Interação por voz, toque e recursos multimídia",
            "Apoio a atividades de IA, programação e inovação",
            "Experiências pedagógicas com mediação humana",
            "Demonstrações institucionais e feiras de tecnologia",
            "Implantação com atenção a LGPD e uso responsável de dados",
        ],
        "purpose_title": "Robótica pedagógica com propósito",
        "purpose": "O LIRO deve ser aplicado com plano de aula, objetivo pedagógico, supervisão e contexto institucional. A tecnologia funciona melhor quando ajuda educadores a conduzir experiências guiadas, conectadas à realidade da turma e às políticas da instituição.",
        "approach_title": "Nossa abordagem com o LIRO",
        "approach": [
            "A Smart Control Brasil atua em diagnóstico, demonstração, alinhamento com a escola, implantação, orientação operacional e evolução para projetos com IA, automação e dados.",
            "Antes de recomendar qualquer caminho, avaliamos objetivo pedagógico, público, infraestrutura, governança de dados e rotina de uso.",
        ],
        "tags": ["Educação", "Robótica pedagógica", "IA responsável", "Metodologias ativas", "Inclusão", "Espaço maker"],
        "faq": [
            ("O LIRO substitui o professor?", "Não. Ele amplia a mediação e funciona melhor com planejamento pedagógico."),
            ("O LIRO pode ser usado com crianças?", "Sim, desde que haja supervisão, consentimento quando aplicável e regras claras de privacidade."),
            ("É necessário ter laboratório de robótica?", "Não obrigatoriamente. A aplicação pode começar com demonstrações, projetos maker e atividades guiadas."),
            ("A Smart Control Brasil presta suporte?", "A Smart Control Brasil apoia diagnóstico, orientação, integração e encaminhamento consultivo conforme o escopo do projeto."),
        ],
    },
    {
        "slug": "neobot",
        "name": "NeoBot",
        "short_name": "NeoBot",
        "subtitle": "Robô de recepção e atendimento para comunicação institucional, orientação de visitantes e experiências de relacionamento.",
        "image": "institutional/eitech/img/all-images/blog/banner-neo.webp",
        "secondary_images": ["institutional/eitech/img/elements/neo-recepicionista-robot.png", "institutional/eitech/img/all-images/team/neobot.webp"],
        "intro": [
            "O NeoBot é um robô de recepção da Xyron Robotics voltado a empresas, escolas, clínicas, eventos, showrooms e ambientes que precisam orientar pessoas com mais presença tecnológica.",
            "Ele pode apoiar boas-vindas, apresentação de informações, direcionamento de visitantes e comunicação institucional, sempre como complemento ao atendimento humano e à operação local.",
        ],
        "benefits": ["Recepção e boas-vindas a visitantes", "Comunicação institucional em eventos e showrooms", "Apoio a clínicas, escolas e empresas", "Apresentação de produtos, serviços e orientações", "Experiência interativa com supervisão da equipe", "Implantação alinhada à privacidade e ao fluxo do ambiente"],
        "purpose_title": "Atendimento presencial com experiência guiada",
        "purpose": "O NeoBot faz mais sentido quando existe uma jornada clara: quem será atendido, quais mensagens devem ser exibidas, quais dúvidas serão direcionadas e quando a equipe humana deve assumir o contato.",
        "approach_title": "Nossa abordagem com o NeoBot",
        "approach": ["A Smart Control Brasil avalia o ambiente, o fluxo de visitantes, os pontos de interação e a comunicação desejada antes de propor a aplicação do NeoBot.", "Também orientamos integração com conteúdos, rotinas de atendimento e boas práticas de privacidade quando houver captura ou consulta de informações."],
        "tags": ["Recepção", "Eventos", "Showroom", "Atendimento", "Comunicação", "Experiência"],
        "faq": [("O NeoBot substitui recepcionistas?", "Não. Ele apoia a experiência e ajuda em orientações repetitivas, mas deve operar com supervisão e fluxo de atendimento definido."), ("Pode ser usado em eventos?", "Sim. Eventos, feiras e showrooms são cenários naturais quando há roteiro, conteúdo e equipe de apoio."), ("É possível personalizar mensagens?", "A personalização depende do escopo, mas o projeto deve prever conteúdo, idioma, jornada e limites de atendimento."), ("A Smart Control Brasil ajuda na implantação?", "Sim. Apoiamos diagnóstico, orientação técnica e alinhamento consultivo conforme o cenário." )],
    },
    {
        "slug": "buddy",
        "name": "Buddy",
        "short_name": "Buddy",
        "subtitle": "Robô compacto e social para interação, demonstrações, educação, eventos e aproximação humano-robô.",
        "image": "institutional/eitech/img/all-images/blog/banner-budybot.webp",
        "secondary_images": ["institutional/eitech/img/elements/budy-dog-robot.png", "institutional/eitech/img/all-images/team/budy.webp"],
        "intro": ["O Buddy é uma solução robótica compacta para interação social, demonstrações tecnológicas, educação e experiências de aproximação entre pessoas e robôs.", "Ele pode apoiar apresentações, atividades educativas, eventos e ações institucionais, desde que o uso seja planejado e acompanhado por responsáveis pelo ambiente."],
        "benefits": ["Interação social e demonstrações tecnológicas", "Apoio a ações educacionais e eventos", "Experiência de aproximação humano-robô", "Uso em ambientes controlados e supervisionados", "Conteúdo e roteiro ajustados ao público", "Implantação com orientação técnica e operacional"],
        "purpose_title": "Robótica social para despertar interesse",
        "purpose": "O Buddy funciona bem quando o objetivo é criar contato acessível com robótica, estimular curiosidade e apoiar atividades conduzidas por pessoas, sem transformar a tecnologia em promessa isolada.",
        "approach_title": "Nossa abordagem com o Buddy",
        "approach": ["A Smart Control Brasil ajuda a entender público, ambiente, roteiro de uso e necessidades de demonstração.", "O projeto pode evoluir para integração com outras soluções Xyron, automação e dados conforme a maturidade da instituição."],
        "tags": ["Interação", "Educação", "Eventos", "Demonstração", "Robótica social", "Inovação"],
        "faq": [("O Buddy é indicado para escolas?", "Pode ser, principalmente em demonstrações e projetos educativos com mediação humana."), ("Ele substitui atendimento humano?", "Não. O foco é apoio à interação, demonstração e engajamento."), ("Precisa de roteiro de uso?", "Sim. Um roteiro claro melhora a experiência e reduz improvisos na operação."), ("Vocês apoiam eventos com robôs?", "A Smart Control Brasil pode orientar escopo, demonstração e operação conforme o projeto." )],
    },
    {
        "slug": "patrol-orbit",
        "name": "Patrol / Orbit",
        "short_name": "Patrol / Orbit",
        "subtitle": "Robôs para segurança patrimonial, rondas, inspeção e monitoramento assistido em ambientes corporativos e condominiais.",
        "image": "institutional/eitech/img/all-images/blog/banner-orbitbot.webp",
        "secondary_images": ["institutional/eitech/img/all-images/about/orbit-robot-security-xyron.png", "institutional/eitech/img/all-images/about/orbit-robot-security-xyron-02.png"],
        "intro": ["Patrol / Orbit reúne soluções Xyron voltadas a rondas, inspeção, presença ostensiva e monitoramento assistido em áreas internas ou externas conforme o modelo e o ambiente.", "A proposta não é substituir completamente equipes de segurança, mas ampliar cobertura, padronizar rotas e apoiar a tomada de decisão com presença robótica e dados operacionais."],
        "benefits": ["Rondas e presença ostensiva assistida", "Apoio à segurança patrimonial e condominial", "Monitoramento em ambientes corporativos", "Inspeções com rotas e critérios definidos", "Integração consultiva com protocolos da equipe", "Uso responsável de imagens, alertas e dados"],
        "purpose_title": "Segurança assistida com processo claro",
        "purpose": "Robôs de patrulha precisam de rotas, responsabilidades, protocolos de resposta, critérios de alerta e alinhamento com a equipe humana para gerar valor real na operação.",
        "approach_title": "Nossa abordagem com Patrol / Orbit",
        "approach": ["A Smart Control Brasil avalia riscos, áreas de circulação, conectividade, pontos de monitoramento e integração com rotinas já existentes.", "Também orientamos o uso responsável de dados, imagens e alertas conforme governança e privacidade do local."],
        "tags": ["Segurança", "Rondas", "Inspeção", "Condomínios", "Monitoramento", "Operação assistida"],
        "faq": [("Patrol / Orbit substitui vigilantes?", "Não. O posicionamento recomendado é apoio à equipe, ampliação de cobertura e padronização de rondas."), ("Pode operar em condomínios?", "Pode ser avaliado para condomínios, empresas e ambientes corporativos conforme infraestrutura e fluxo."), ("Precisa integrar com central de segurança?", "Depende do escopo. A integração deve ser estudada com os protocolos da operação."), ("Há cuidados com imagens e dados?", "Sim. Privacidade, LGPD e regras de retenção precisam ser considerados desde o diagnóstico." )],
    },
    {
        "slug": "hygibot",
        "name": "HygiBot",
        "short_name": "HygiBot",
        "subtitle": "Robô de limpeza e higienização para padronizar rotinas em ambientes comerciais, educacionais, hospitalares e condominiais.",
        "image": "institutional/eitech/img/all-images/blog/banner-hygibot.webp",
        "secondary_images": ["institutional/eitech/img/all-images/blog/banner-hygibot.webp", "institutional/eitech/img/all-images/about/robots-xyron.png"],
        "intro": ["O HygiBot é uma solução Xyron para apoiar rotinas de limpeza e higienização em shoppings, escolas, hospitais, clínicas, condomínios e ambientes comerciais.", "A aplicação deve ser pensada como apoio operacional para padronização, previsibilidade e organização da equipe, não como substituição automática de todo o processo de limpeza."],
        "benefits": ["Apoio a rotinas de limpeza padronizadas", "Uso em escolas, clínicas, shoppings e condomínios", "Melhor previsibilidade operacional", "Redução de deslocamentos repetitivos", "Planejamento por áreas, horários e prioridades", "Orientação técnica para operação e manutenção"],
        "purpose_title": "Higienização com rotina e acompanhamento",
        "purpose": "O HygiBot deve entrar em um processo com áreas definidas, frequência planejada, supervisão, insumos adequados e indicadores simples de acompanhamento.",
        "approach_title": "Nossa abordagem com o HygiBot",
        "approach": ["A Smart Control Brasil analisa área, piso, fluxo de pessoas, rotina atual e limitações do ambiente antes de indicar o uso do HygiBot.", "O foco é ajudar a operação a ganhar padronização com tecnologia viável e treinamento compatível com a equipe."],
        "tags": ["Limpeza", "Higienização", "Hospitais", "Escolas", "Condomínios", "Padronização"],
        "faq": [("O HygiBot substitui a equipe de limpeza?", "Não. Ele apoia rotinas e pode reduzir esforço repetitivo, mas exige supervisão e processo definido."), ("Pode ser usado em hospitais?", "Pode ser avaliado, respeitando protocolos, áreas permitidas e regras de higiene do local."), ("Precisa mapear o ambiente?", "Sim. O diagnóstico do espaço é essencial para definir viabilidade e rotina."), ("A Smart Control Brasil orienta a operação?", "Sim. Apoiamos diagnóstico, implantação consultiva e orientação conforme o escopo." )],
    },
    {
        "slug": "hostbot",
        "name": "HostBot",
        "short_name": "HostBot",
        "subtitle": "Robô host para hospitalidade, recepção, eventos, restaurantes, hotéis, clínicas e orientação de visitantes.",
        "image": "institutional/eitech/img/all-images/blog/banner-hostbot.webp",
        "secondary_images": ["institutional/eitech/img/all-images/hero/hostbot.png", "institutional/eitech/img/all-images/hero/hostbot-bot.png"],
        "intro": ["O HostBot é uma solução Xyron para recepção e hospitalidade em eventos, restaurantes, hotéis, clínicas, empresas e ambientes que recebem visitantes com frequência.", "Ele pode apoiar orientação, apresentação de informações e experiências de boas-vindas, sempre com fluxo definido e equipe humana por perto quando necessário."],
        "benefits": ["Recepção e hospitalidade assistida", "Orientação de visitantes e clientes", "Apoio a eventos, hotéis e restaurantes", "Experiências institucionais mais interativas", "Mensagens e jornada alinhadas ao ambiente", "Operação com supervisão e regras claras"],
        "purpose_title": "Hospitalidade com tecnologia assistiva",
        "purpose": "O HostBot deve ser aplicado onde a experiência de chegada, orientação e comunicação pode ser melhorada por um ponto interativo, sem perder acolhimento humano.",
        "approach_title": "Nossa abordagem com o HostBot",
        "approach": ["A Smart Control Brasil ajuda a mapear jornada, local de circulação, conteúdo de atendimento e necessidades de integração.", "A recomendação considera infraestrutura, equipe, privacidade e experiência real dos visitantes."],
        "tags": ["Hospitalidade", "Recepção", "Eventos", "Hotéis", "Restaurantes", "Visitantes"],
        "faq": [("HostBot é só para eventos?", "Não. Também pode ser avaliado para hotéis, clínicas, restaurantes, empresas e recepções."), ("Ele responde qualquer pergunta?", "O ideal é delimitar conteúdo, jornada e transferência para equipe humana quando necessário."), ("Pode orientar visitantes?", "Sim, desde que o fluxo e as informações estejam bem definidos."), ("Vocês ajudam a desenhar a jornada?", "Sim. Esse alinhamento faz parte do diagnóstico consultivo." )],
    },
    {
        "slug": "waiterbot",
        "name": "WaiterBot",
        "short_name": "WaiterBot",
        "subtitle": "Robô de apoio ao atendimento de salão e entrega interna para restaurantes, bares, hotéis, eventos e ambientes de serviço.",
        "image": "institutional/eitech/img/all-images/blog/banner-waiterbot.webp",
        "secondary_images": ["institutional/eitech/img/all-images/about/relay-robot-entrega-xyron.png", "institutional/eitech/img/all-images/blog/banner-waiterbot.webp"],
        "intro": ["O WaiterBot é um robô de apoio operacional para deslocamento e entrega de itens dentro de restaurantes, bares, hotéis, eventos e ambientes de atendimento.", "Ele não deve ser tratado como substituto completo de garçons. Seu melhor uso é reduzir deslocamentos repetitivos e apoiar a equipe em fluxos bem definidos."],
        "benefits": ["Apoio à entrega interna de itens", "Uso em restaurantes, hotéis, bares e eventos", "Redução de deslocamentos repetitivos", "Fluxos definidos por pontos de retirada e entrega", "Operação assistida pela equipe de salão", "Diagnóstico de layout antes da implantação"],
        "purpose_title": "Atendimento de salão com apoio operacional",
        "purpose": "O WaiterBot depende de layout, circulação, pontos de entrega, rotina da equipe e sinalização clara para funcionar de forma organizada e útil.",
        "approach_title": "Nossa abordagem com o WaiterBot",
        "approach": ["A Smart Control Brasil avalia fluxo de salão, distância entre pontos, obstáculos, rotina de atendimento e experiência desejada.", "A proposta é apoiar produtividade e padronização sem perder qualidade no contato humano com o cliente."],
        "tags": ["Restaurantes", "Hotéis", "Eventos", "Entrega interna", "Salão", "Operação"],
        "faq": [("WaiterBot substitui garçons?", "Não. Ele apoia deslocamentos e entregas, enquanto a equipe mantém atendimento, relacionamento e decisões."), ("Precisa adaptar o salão?", "Pode ser necessário ajustar rotas, pontos de entrega e organização do fluxo."), ("Funciona em eventos?", "Pode ser avaliado para eventos com trajetos claros e operação supervisionada."), ("A Smart Control Brasil faz diagnóstico?", "Sim. O diagnóstico do ambiente é recomendado antes de qualquer proposta." )],
    },
    {
        "slug": "carebot",
        "name": "CareBot",
        "short_name": "CareBot",
        "subtitle": "Robô de cuidado assistido para clínicas, hospitais, casas de repouso e ambientes de apoio a equipes e pacientes.",
        "image": "institutional/eitech/img/all-images/blog/banner-carebot.webp",
        "secondary_images": ["institutional/eitech/img/all-images/blog/banner-carebot.webp", "institutional/eitech/img/all-images/about/robots-xyron.png"],
        "intro": ["O CareBot é uma solução Xyron voltada a cuidado assistido, interação, orientação e apoio operacional em clínicas, hospitais, casas de repouso e ambientes de saúde.", "Ele não realiza promessa médica. Seu papel deve ser avaliado como apoio à equipe, humanização tecnológica e organização de interações conforme protocolos do local."],
        "benefits": ["Apoio a clínicas, hospitais e casas de repouso", "Interação e orientação assistida", "Humanização tecnológica com supervisão", "Apoio a equipes em rotinas informativas", "Uso alinhado a protocolos do ambiente", "Atenção a privacidade, consentimento e LGPD"],
        "purpose_title": "Cuidado assistido sem promessa médica",
        "purpose": "O CareBot deve respeitar protocolos clínicos, privacidade, consentimento e limites de atuação. A tecnologia apoia pessoas, mas não substitui julgamento profissional de saúde.",
        "approach_title": "Nossa abordagem com o CareBot",
        "approach": ["A Smart Control Brasil conduz uma análise consultiva do ambiente, do público, dos protocolos e da governança de dados antes de recomendar a aplicação.", "O objetivo é identificar usos seguros, úteis e compatíveis com a rotina da instituição."],
        "tags": ["Cuidado assistido", "Clínicas", "Hospitais", "Casas de repouso", "Humanização", "LGPD"],
        "faq": [("CareBot realiza atendimento médico?", "Não. Ele pode apoiar orientação e interação, mas não substitui profissionais ou protocolos de saúde."), ("Pode ser usado com idosos?", "Pode ser avaliado em casas de repouso e cuidado assistido, com supervisão e regras claras."), ("Há cuidados com dados pessoais?", "Sim. Privacidade, consentimento e LGPD devem ser tratados desde o diagnóstico."), ("Vocês fazem integração com rotinas da clínica?", "A Smart Control Brasil pode orientar integração e operação conforme escopo e viabilidade." )],
    },
    {
        "slug": "mowerbot",
        "name": "MowerBot",
        "short_name": "MowerBot",
        "subtitle": "Robô cortador de grama para áreas externas, condomínios, clubes, escolas, hotéis e manutenção paisagística automatizada.",
        "image": "institutional/eitech/img/all-images/blog/banner-mowerbot.webp",
        "secondary_images": ["institutional/eitech/img/all-images/blog/banner-mowerbot.webp", "institutional/eitech/img/all-images/about/robots-xyron.png"],
        "intro": ["O MowerBot é uma solução Xyron para corte de grama e apoio à manutenção paisagística em áreas externas como condomínios, clubes, escolas, hotéis, áreas corporativas, jardins e pequenas propriedades.", "Ele deve ser posicionado como apoio para produtividade, padronização e redução de esforço operacional, sempre após avaliação do terreno, segurança e rotina de manutenção."],
        "benefits": ["Corte de grama em áreas externas planejadas", "Apoio a condomínios, clubes, hotéis e escolas", "Padronização da manutenção paisagística", "Redução de esforço em tarefas repetitivas", "Avaliação de terreno, inclinação e obstáculos", "Operação com critérios de segurança e supervisão"],
        "purpose_title": "Manutenção paisagística com processo e segurança",
        "purpose": "O MowerBot funciona melhor quando o terreno, as rotas, horários, áreas de risco e critérios de supervisão são definidos antes da operação regular.",
        "approach_title": "Nossa abordagem com o MowerBot",
        "approach": ["A Smart Control Brasil avalia área, inclinação, obstáculos, rotina de jardinagem, pontos de carga e restrições de segurança.", "A proposta considera produtividade, padronização e aderência ao ambiente antes de qualquer recomendação comercial."],
        "tags": ["Corte de grama", "Áreas externas", "Condomínios", "Clubes", "Hotéis", "Paisagismo"],
        "faq": [("MowerBot serve para qualquer terreno?", "Não necessariamente. É preciso avaliar inclinação, obstáculos, tipo de área e condições de segurança."), ("Ele substitui toda a jardinagem?", "Não. Ele apoia o corte de grama e pode reduzir esforço, mas a rotina paisagística continua exigindo planejamento."), ("Pode ser usado em condomínios?", "Pode ser avaliado para condomínios, clubes, escolas, hotéis e áreas corporativas."), ("A Smart Control Brasil faz avaliação do local?", "Sim. O diagnóstico do terreno e da operação é parte importante da recomendação." )],
    },
]



XYRON_ROBOT_DETAILS = {
    "liro-littlebot": {
        "summary": "Robô educacional para escolas, espaços maker e experiências de IA com mediação humana.",
        "primary_application": "Educação, robótica pedagógica e projetos maker",
        "functions": [
            "Interação educacional com estudantes e educadores",
            "Apoio a atividades pedagógicas e projetos maker",
            "Conversas assistidas e demonstrações de IA",
            "Experiências de robótica com mediação do professor",
            "Apoio a apresentações, feiras e aulas guiadas",
            "Uso consultivo em inclusão e engajamento escolar",
        ],
        "technical_specs": [
            ("Categoria", "Robô educacional/interativo"),
            ("Aplicação principal", "Experiências pedagógicas com robótica e IA"),
            ("Ambiente indicado", "Escolas, laboratórios, espaços maker e projetos educacionais"),
            ("Tipo de operação", "Uso assistido com mediação humana"),
            ("Observações", "Recursos e configuração devem ser confirmados conforme modelo e escopo do projeto"),
        ],
        "ideal_for": ["Escolas", "Espaços maker", "Projetos educacionais", "Feiras de tecnologia"],
        "commercial_notes": "A recomendação depende de objetivo pedagógico, idade do público, infraestrutura, governança de dados e rotina de uso. O LIRO não substitui o professor.",
    },
    "neobot": {
        "summary": "Robô de recepção e comunicação institucional para visitantes, eventos e showrooms.",
        "primary_application": "Recepção, atendimento inicial e orientação de visitantes",
        "functions": [
            "Recepção e boas-vindas",
            "Orientação de visitantes",
            "Comunicação institucional",
            "Apresentação de serviços e informações",
            "Apoio em eventos, feiras e showrooms",
            "Direcionamento para equipe humana quando necessário",
        ],
        "technical_specs": [
            ("Categoria", "Robô de recepção e atendimento"),
            ("Aplicação principal", "Orientação e interação com visitantes"),
            ("Ambiente indicado", "Empresas, escolas, clínicas, eventos, lojas e showrooms"),
            ("Tipo de operação", "Atendimento assistido com roteiro e supervisão"),
            ("Observações", "Recursos de idioma, conteúdo e integração variam conforme configuração e escopo"),
        ],
        "ideal_for": ["Recepções corporativas", "Eventos", "Showrooms", "Clínicas", "Escolas"],
        "commercial_notes": "A implantação deve definir jornada, mensagens, limites de atendimento e momento de transferência para equipe humana.",
    },
    "buddy": {
        "summary": "Robô compacto/social para interação, demonstração tecnológica e aproximação humano-robô.",
        "primary_application": "Interação, educação, demonstrações e eventos",
        "functions": [
            "Interação social com público",
            "Demonstração tecnológica",
            "Atendimento leve e guiado",
            "Apoio educacional e institucional",
            "Aproximação humano-robô",
            "Presença em eventos e ações de inovação",
        ],
        "technical_specs": [
            ("Categoria", "Robô social/interativo"),
            ("Aplicação principal", "Demonstração, interação e apoio educacional"),
            ("Ambiente indicado", "Escolas, eventos, empresas e ambientes controlados"),
            ("Tipo de operação", "Uso supervisionado com roteiro de interação"),
            ("Observações", "Configuração, autonomia e acessórios devem ser confirmados conforme modelo e fornecimento"),
        ],
        "ideal_for": ["Eventos", "Escolas", "Demonstrações", "Ações institucionais"],
        "commercial_notes": "O Buddy deve ser posicionado como apoio à interação e demonstração, não como solução isolada para atendimento ou segurança.",
    },
    "patrol-orbit": {
        "summary": "Robôs para rondas, inspeção e monitoramento assistido em segurança patrimonial.",
        "primary_application": "Segurança patrimonial, rondas e inspeção assistida",
        "functions": [
            "Rondas assistidas",
            "Presença ostensiva em áreas definidas",
            "Inspeção de áreas internas ou externas conforme ambiente",
            "Apoio ao monitoramento e registro operacional",
            "Integração consultiva com rotinas de segurança",
            "Apoio à padronização de rotas e critérios de alerta",
        ],
        "technical_specs": [
            ("Categoria", "Robô de patrulhamento e inspeção"),
            ("Aplicação principal", "Rondas e monitoramento assistido"),
            ("Ambiente indicado", "Condomínios, empresas, áreas corporativas, estacionamentos e ambientes mapeados"),
            ("Tipo de operação", "Rotas e protocolos definidos com a equipe de segurança"),
            ("Observações", "Sensores, integração e recursos de monitoramento devem ser confirmados conforme modelo e escopo"),
        ],
        "ideal_for": ["Condomínios", "Empresas", "Áreas amplas", "Operações com rondas"],
        "commercial_notes": "A proposta é apoiar equipes de segurança, ampliar cobertura e padronizar rondas, sem substituir integralmente vigilantes ou protocolos humanos.",
    },
    "hygibot": {
        "summary": "Robô para apoiar limpeza e higienização em áreas comerciais, institucionais e de alto fluxo.",
        "primary_application": "Limpeza, higienização e padronização de rotinas",
        "functions": [
            "Apoio a limpeza e higienização",
            "Padronização de rotinas por área",
            "Apoio em grandes áreas internas",
            "Redução de esforço operacional repetitivo",
            "Uso em ambientes comerciais e institucionais",
            "Acompanhamento com processo e supervisão definidos",
        ],
        "technical_specs": [
            ("Categoria", "Robô de limpeza/higienização"),
            ("Aplicação principal", "Rotinas de limpeza assistida"),
            ("Ambiente indicado", "Escolas, clínicas, hospitais, shoppings, condomínios e ambientes comerciais"),
            ("Tipo de operação", "Uso planejado por áreas, horários e protocolos"),
            ("Observações", "Funções, insumos, autonomia e compatibilidade com piso variam conforme modelo e ambiente"),
        ],
        "ideal_for": ["Shoppings", "Escolas", "Hospitais", "Clínicas", "Condomínios"],
        "commercial_notes": "O HygiBot apoia a equipe de limpeza e exige supervisão, protocolos e diagnóstico do espaço antes da proposta.",
    },
    "hostbot": {
        "summary": "Robô host para hospitalidade, recepção, orientação e experiências em eventos.",
        "primary_application": "Recepção, hospitalidade e orientação de visitantes",
        "functions": [
            "Recepção e hospitalidade",
            "Orientação de visitantes",
            "Atendimento inicial com roteiro definido",
            "Apoio em eventos e feiras",
            "Apresentação de informações institucionais",
            "Encaminhamento para equipe humana quando necessário",
        ],
        "technical_specs": [
            ("Categoria", "Robô host/interativo"),
            ("Aplicação principal", "Hospitalidade e recepção assistida"),
            ("Ambiente indicado", "Eventos, hotéis, restaurantes, clínicas, empresas e recepções"),
            ("Tipo de operação", "Jornada guiada com conteúdo e supervisão"),
            ("Observações", "Telas, idiomas, conteúdos e integrações devem ser confirmados conforme configuração"),
        ],
        "ideal_for": ["Eventos", "Hotéis", "Restaurantes", "Clínicas", "Recepções"],
        "commercial_notes": "O HostBot melhora a experiência de chegada e orientação, mas não substitui acolhimento humano nem atendimento especializado.",
    },
    "waiterbot": {
        "summary": "Robô de apoio ao salão para transporte interno de itens em restaurantes, hotéis e eventos.",
        "primary_application": "Apoio ao atendimento de salão e entrega interna",
        "functions": [
            "Apoio ao atendimento de salão",
            "Transporte interno de itens",
            "Apoio a garçons e equipe operacional",
            "Redução de deslocamentos repetitivos",
            "Operação em restaurantes, hotéis e eventos",
            "Melhoria de fluxo interno com rotas definidas",
        ],
        "technical_specs": [
            ("Categoria", "Robô de apoio a entregas internas"),
            ("Aplicação principal", "Transporte assistido de itens no salão"),
            ("Ambiente indicado", "Restaurantes, hotéis, bares, eventos e ambientes de serviço"),
            ("Tipo de operação", "Rotas internas com pontos de retirada e entrega"),
            ("Observações", "Capacidade, autonomia e recursos de navegação variam conforme modelo, layout e escopo"),
        ],
        "ideal_for": ["Restaurantes", "Hotéis", "Eventos", "Bares", "Food service"],
        "commercial_notes": "O WaiterBot apoia deslocamentos e entregas. Não deve ser vendido como substituto completo de garçons ou da equipe de salão.",
    },
    "carebot": {
        "summary": "Robô de cuidado assistido para interação, orientação e apoio a equipes em ambientes de saúde.",
        "primary_application": "Cuidado assistido e humanização tecnológica",
        "functions": [
            "Apoio assistido e interação",
            "Orientação em rotinas informativas",
            "Lembretes operacionais conforme escopo",
            "Apoio à equipe em fluxos definidos",
            "Humanização tecnológica",
            "Atenção a privacidade, consentimento e protocolos",
        ],
        "technical_specs": [
            ("Categoria", "Robô de cuidado assistido"),
            ("Aplicação principal", "Apoio à interação e orientação em ambientes de cuidado"),
            ("Ambiente indicado", "Clínicas, hospitais, casas de repouso e instituições de cuidado"),
            ("Tipo de operação", "Uso assistido conforme protocolos do local"),
            ("Observações", "Recursos de interação, monitoramento e integração devem ser avaliados conforme modelo, privacidade e escopo"),
        ],
        "ideal_for": ["Clínicas", "Hospitais", "Casas de repouso", "Cuidado assistido"],
        "commercial_notes": "O CareBot não realiza promessa médica e não substitui profissionais de saúde, cuidadores ou protocolos clínicos.",
    },
    "mowerbot": {
        "summary": "Robô para corte de grama e apoio à manutenção paisagística em áreas externas.",
        "primary_application": "Corte de grama e manutenção externa assistida",
        "functions": [
            "Corte de grama em áreas planejadas",
            "Apoio à manutenção paisagística",
            "Padronização de áreas externas",
            "Redução de esforço repetitivo",
            "Operação em condomínios, clubes, escolas, hotéis e áreas corporativas",
            "Apoio à produtividade de equipes externas",
        ],
        "technical_specs": [
            ("Categoria", "Robô cortador de grama"),
            ("Aplicação principal", "Corte de grama e apoio à manutenção paisagística"),
            ("Ambiente indicado", "Condomínios, clubes, escolas, hotéis, áreas corporativas, jardins e pequenas propriedades"),
            ("Tipo de operação", "Uso planejado após avaliação do terreno"),
            ("Observações", "Capacidade, inclinação, autonomia e recursos devem ser confirmados conforme modelo, terreno e escopo"),
        ],
        "ideal_for": ["Condomínios", "Clubes", "Escolas", "Hotéis", "Áreas corporativas", "Jardins"],
        "commercial_notes": "O MowerBot apoia produtividade e padronização, mas depende de avaliação do terreno, segurança e rotina de manutenção.",
    },
}

for robot in XYRON_ROBOTS:
    robot.update(XYRON_ROBOT_DETAILS.get(robot["slug"], {}))

XYRON_ROBOTS_BY_SLUG = {robot["slug"]: robot for robot in XYRON_ROBOTS}


def get_xyron_robot(slug):
    return XYRON_ROBOTS_BY_SLUG.get(slug)


def get_other_xyron_robots(slug):
    return [robot for robot in XYRON_ROBOTS if robot["slug"] != slug]


def get_featured_xyron_robots(slug, limit=3):
    return get_other_xyron_robots(slug)[:limit]
