# Generated by Django 6.0.4 on 2026-05-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_action_391715_idx',
            old_name='audit_logs_action_6dc4c0_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_entity_22e216_idx',
            old_name='audit_logs_entity_59fa67_idx',
        ),
    ]
