from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0002_sitemembership"),
        ("smart_system", "0009_maintenance_contracts"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentDefinition",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("domain", models.CharField(choices=[("maintenance", "Maintenance"), ("scheduling", "Scheduling"), ("profitability", "Profitability"), ("marketplace", "Marketplace"), ("anomaly", "Anomaly"), ("platform", "Platform")], db_index=True, max_length=40)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("disabled", "Disabled"), ("archived", "Archived")], default="draft", max_length=20)),
                ("autonomy_level", models.PositiveSmallIntegerField(choices=[(0, "Level 0 - Passive"), (1, "Level 1 - Recommendation"), (2, "Level 2 - Proposal"), (3, "Level 3 - Auto Execute")], default=1)),
                ("enabled", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "ai_agents_definitions", "ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="AgentExecutionPolicy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("require_human_approval", models.BooleanField(default=True)),
                ("allow_manual_runs", models.BooleanField(default=True)),
                ("allow_scheduled_runs", models.BooleanField(default=True)),
                ("enforce_billing_active", models.BooleanField(default=True)),
                ("allowed_tools", models.JSONField(blank=True, default=list)),
                ("allowed_action_types", models.JSONField(blank=True, default=list)),
                ("max_recommendations", models.PositiveIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="execution_policy", to="ai_agents_center.agentdefinition")),
            ],
            options={"db_table": "ai_agents_execution_policies", "ordering": ["agent__name"]},
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("trigger_type", models.CharField(choices=[("manual", "Manual"), ("event", "Event"), ("scheduled", "Scheduled"), ("api", "API")], db_index=True, max_length=20)),
                ("trigger_reference", models.CharField(blank=True, db_index=True, max_length=180)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=20)),
                ("input_context", models.JSONField(blank=True, default=dict)),
                ("output_summary", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("correlation_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="ai_agents_center.agentdefinition")),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="agent_runs", to="companies.company")),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_runs", to="smart_system.operationalsite")),
                ("triggered_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="triggered_agent_runs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "ai_agents_runs", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AgentRecommendation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("recommendation_type", models.CharField(choices=[("insight", "Insight"), ("preventive", "Preventive"), ("rebalancing", "Rebalancing"), ("profitability", "Profitability"), ("marketplace", "Marketplace"), ("anomaly", "Anomaly")], db_index=True, max_length=30)),
                ("title", models.CharField(max_length=240)),
                ("summary", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], db_index=True, default="medium", max_length=20)),
                ("status", models.CharField(choices=[("open", "Open"), ("reviewed", "Reviewed"), ("accepted", "Accepted"), ("dismissed", "Dismissed"), ("applied", "Applied")], db_index=True, default="open", max_length=20)),
                ("entity_type", models.CharField(blank=True, db_index=True, max_length=80)),
                ("entity_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recommendations", to="ai_agents_center.agentrun")),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="agent_recommendations", to="companies.company")),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_recommendations", to="smart_system.operationalsite")),
            ],
            options={"db_table": "ai_agents_recommendations", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AgentActionProposal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("action_type", models.CharField(db_index=True, max_length=80)),
                ("target_entity", models.CharField(blank=True, db_index=True, max_length=80)),
                ("target_entity_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("proposed_payload", models.JSONField(blank=True, default=dict)),
                ("approval_required", models.BooleanField(default=True)),
                ("status", models.CharField(choices=[("pending_approval", "Pending Approval"), ("approved", "Approved"), ("rejected", "Rejected"), ("executed", "Executed"), ("cancelled", "Cancelled")], db_index=True, default="pending_approval", max_length=30)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="action_proposals", to="ai_agents_center.agentrun")),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_agent_action_proposals", to=settings.AUTH_USER_MODEL)),
                ("rejected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rejected_agent_action_proposals", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "ai_agents_action_proposals", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AgentMemoryEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("entity_type", models.CharField(blank=True, db_index=True, max_length=80)),
                ("entity_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("memory_kind", models.CharField(choices=[("entity_summary", "Entity Summary"), ("tenant_context", "Tenant Context"), ("analytics_snapshot", "Analytics Snapshot"), ("operations_summary", "Operations Summary"), ("recommendation_feedback", "Recommendation Feedback")], db_index=True, max_length=40)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memory_entries", to="ai_agents_center.agentdefinition")),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="agent_memory_entries", to="companies.company")),
                ("site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="agent_memory_entries", to="smart_system.operationalsite")),
            ],
            options={"db_table": "ai_agents_memory_entries", "ordering": ["-created_at"]},
        ),
    ]
