# Generated by Codex on 2026-06-19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents_center", "0012_remove_managercopilotconfiguration_uniq_ai_manager_copilot_configuration_company_and_more"),
        ("companies", "0003_company_city_state"),
        ("growth_engine", "0002_commercialproposal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommercialOpportunity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("company_name", models.CharField(max_length=180)),
                ("segment", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(choices=[("manual", "Manual"), ("website", "Website"), ("linkedin", "LinkedIn"), ("instagram", "Instagram"), ("google_maps", "Google Maps"), ("partner", "Partner"), ("event", "Event"), ("public_data", "Public Data")], db_index=True, default="manual", max_length=30)),
                ("title", models.CharField(max_length=240)),
                ("problem_detected", models.TextField()),
                ("opportunity_description", models.TextField(blank=True)),
                ("recommended_solution", models.TextField(blank=True)),
                ("recommended_product", models.CharField(blank=True, max_length=240)),
                ("commercial_score", models.PositiveSmallIntegerField(db_index=True, default=0)),
                ("confidence_score", models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=3)),
                ("status", models.CharField(choices=[("new", "New"), ("enriching", "Enriching"), ("ready_for_review", "Ready for Review"), ("approved", "Approved"), ("rejected", "Rejected"), ("converted_to_lead", "Converted to Lead")], db_index=True, default="new", max_length=30)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="commercial_opportunities", to="ai_agents_center.agentrun")),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="commercial_opportunities", to="companies.company")),
                ("converted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="converted_commercial_opportunities", to=settings.AUTH_USER_MODEL)),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="commercial_opportunities", to="growth_engine.lead")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_commercial_opportunities", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "ai_agents_commercial_opportunities",
                "ordering": ["-commercial_score", "-confidence_score", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="commercialopportunity",
            index=models.Index(fields=["status", "commercial_score"], name="ai_comm_opp_status_score_idx"),
        ),
        migrations.AddIndex(
            model_name="commercialopportunity",
            index=models.Index(fields=["source", "created_at"], name="ai_comm_opp_source_created_idx"),
        ),
    ]
