# Generated by Codex on 2026-06-16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents_center", "0013_commercialopportunity"),
        ("companies", "0003_company_city_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commercialopportunity",
            name="outreach_channel",
            field=models.CharField(
                choices=[("none", "None"), ("email", "Email")],
                db_index=True,
                default="none",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="commercialopportunity",
            name="outreach_domain",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="commercialopportunity",
            name="outreach_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="commercialopportunity",
            name="outreach_sender_email",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="commercialopportunity",
            name="outreach_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="not_started",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="commercialopportunity",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("website", "Website"),
                    ("linkedin", "LinkedIn"),
                    ("instagram", "Instagram"),
                    ("google_maps", "Google Maps"),
                    ("partner", "Partner"),
                    ("event", "Event"),
                    ("public_data", "Public Data"),
                    ("csv", "CSV"),
                ],
                db_index=True,
                default="manual",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="EduardoProspectImportBatch",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("source", models.CharField(db_index=True, default="manual", max_length=30)),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("created_opportunities", models.PositiveIntegerField(default=0)),
                ("skipped_duplicates", models.PositiveIntegerField(default=0)),
                ("skipped_empty_rows", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edu_prospect_import_batches",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edu_prospect_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_agents_edu_prospect_import_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="eduardoprospectimportbatch",
            index=models.Index(fields=["status", "created_at"], name="ai_edu_imp_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="eduardoprospectimportbatch",
            index=models.Index(fields=["source", "created_at"], name="ai_edu_imp_source_created_idx"),
        ),
    ]
