# Generated by Django 6.0.4 on 2026-06-21 22:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents_center', '0015_rename_edu_to_atlas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasLead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('segmento', models.CharField(choices=[('Escola / Educação', 'Escola / Educação'), ('Limpeza / Facilities', 'Limpeza / Facilities'), ('Shopping / Clínica / Hotel', 'Shopping / Clínica / Hotel'), ('Segurança / Indústria', 'Segurança / Indústria'), ('Outros', 'Outros')], default='Outros', max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=150)),
                ('regiao', models.CharField(blank=True, max_length=150)),
                ('fit_comercial', models.CharField(blank=True, max_length=50)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('nome_decisor', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_decisor', models.CharField(blank=True, max_length=255, null=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='ready_for_review', max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_agents_atlas_leads',
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
