# Generated by Django 6.0.4 on 2026-06-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents_center', '0016_atlaslead'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAtlasLead',
            fields=[
            ],
            options={
                'verbose_name': 'Lead Pendente do Atlas',
                'verbose_name_plural': 'Leads Pendentes do Atlas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ai_agents_center.atlaslead',),
        ),
    ]
