from copy import deepcopy

from .tenant_scope import filter_records_for_scope, record_matches_scope


ASSET_RECORDS = [
    {
        "code": "CAMARA-CLIMATICA-01",
        "name": "Camara Climatica Principal",
        "description": "Camara para testes ambientais de estabilidade e envelhecimento acelerado.",
        "category": "Utilidades de laboratorio",
        "subcategory": "Camara climatica",
        "manufacturer": "Fitotec",
        "model": "CC-900",
        "serial_number": "FT-CC900-1182",
        "client": "Laboratorio Exemplo",
        "site": "Laboratorio Campinas",
        "sector": "Sala de Ensaios 1",
        "criticality": "Alta",
        "operational_status": "Operacional",
        "condition": "Em atencao",
        "installation_date": "2022-04-12",
        "commissioning_date": "2022-04-20",
        "warranty": "2027-04-20",
        "maintenance_plan": "Plano PM-CC-12",
        "last_maintenance": "2026-03-02",
        "next_maintenance": "2026-03-18",
        "last_preventive": "2026-03-02",
        "next_preventive": "2026-03-18",
        "last_corrective": "2026-02-09",
        "mtbf": "182 h",
        "mttr": "2,8 h",
        "availability": "97,8%",
        "owner": "Fernanda Pires",
        "open_work_orders": 1,
        "recent_failures": 1,
        "without_plan": False,
        "has_open_work_order": True,
        "failure_recidivism": "Baixa",
        "risk_level": "Moderado",
        "impact": "Afeta cronograma de ensaios ambientais premium.",
        "technical_notes": "Recomendada revisão de vedação e calibração semestral dos sensores.",
        "technical_specs": {"tensao": "380 V", "potencia": "5.5 kW", "capacidade": "900 L"},
        "maintenance_summary": {"interventions": 6, "downtime": "8,5 h", "plan_adherence": "94%", "trend": "Estavel"},
        "history": [
            {"timestamp": "12/03 09:14", "type": "OS concluida", "description": "Ajuste de controlador PID e validação térmica.", "owner": "Fernanda Pires", "reference": "OS-2026-0158"},
            {"timestamp": "02/03 08:00", "type": "Preventiva executada", "description": "Checklist semanal, limpeza de condensador e calibração.", "owner": "Equipe LAB", "reference": "PM-CC-12"},
            {"timestamp": "09/02 15:20", "type": "Falha registrada", "description": "Oscilação de umidade acima da faixa operacional.", "owner": "Lucas Neri", "reference": "FE-0081"},
        ],
        "alerts": [
            {"severity": "warning", "title": "Preventiva em 6 dias", "description": "Plano PM-CC-12 entra em janela na próxima semana."},
        ],
    },
    {
        "code": "CHILLER-UNID-A",
        "name": "Chiller Unidade A",
        "description": "Resfriamento central da unidade premium com redundância parcial.",
        "category": "HVAC",
        "subcategory": "Chiller",
        "manufacturer": "Trane",
        "model": "RTAC 285",
        "serial_number": "TR-RTAC-7751",
        "client": "Academia Exemplo",
        "site": "Unidade Centro",
        "sector": "Casa de Maquinas",
        "criticality": "Critica",
        "operational_status": "Operacao degradada",
        "condition": "Critica",
        "installation_date": "2021-09-03",
        "commissioning_date": "2021-09-12",
        "warranty": "2026-09-12",
        "maintenance_plan": "Plano PM-HVAC-01",
        "last_maintenance": "2026-02-27",
        "next_maintenance": "2026-03-16",
        "last_preventive": "2026-02-27",
        "next_preventive": "2026-03-16",
        "last_corrective": "2026-03-11",
        "mtbf": "96 h",
        "mttr": "4,6 h",
        "availability": "91,2%",
        "owner": "Carlos Mota",
        "open_work_orders": 2,
        "recent_failures": 3,
        "without_plan": False,
        "has_open_work_order": True,
        "failure_recidivism": "Alta",
        "risk_level": "Alto",
        "impact": "Risco direto ao conforto térmico e à operação da unidade A.",
        "technical_notes": "Revisar sensores de fluxo e rotina de limpeza do evaporador.",
        "technical_specs": {"tensao": "440 V", "potencia": "85 kW", "capacidade": "285 TR"},
        "maintenance_summary": {"interventions": 11, "downtime": "24,0 h", "plan_adherence": "82%", "trend": "Piorando"},
        "history": [
            {"timestamp": "12/03 07:18", "type": "OS aberta", "description": "Baixa eficiência de resfriamento e alarme de temperatura.", "owner": "Carlos Mota", "reference": "OS-2026-0148"},
            {"timestamp": "11/03 18:42", "type": "Falha registrada", "description": "Oscilação térmica com acionamento parcial do compressor.", "owner": "Equipe HVAC", "reference": "FE-0096"},
            {"timestamp": "27/02 09:00", "type": "Preventiva executada", "description": "Checklist de utilidades e limpeza de serpentina.", "owner": "Equipe HVAC", "reference": "PM-HVAC-01"},
        ],
        "alerts": [
            {"severity": "critical", "title": "Ativo crítico com OS aberta", "description": "OS-2026-0148 em andamento impactando área premium."},
            {"severity": "warning", "title": "Falha reincidente", "description": "Terceira ocorrência de oscilação térmica em 45 dias."},
        ],
    },
    {
        "code": "HVAC-ACADEMIA-02",
        "name": "Rooftop HVAC Academia 02",
        "description": "Condicionamento de ar da área cardio e funcional.",
        "category": "HVAC",
        "subcategory": "Rooftop",
        "manufacturer": "Carrier",
        "model": "48TC",
        "serial_number": "CA-48TC-3350",
        "client": "Academia Exemplo",
        "site": "Unidade Norte",
        "sector": "Cobertura Bloco B",
        "criticality": "Alta",
        "operational_status": "Operacional",
        "condition": "Em atencao",
        "installation_date": "2020-06-18",
        "commissioning_date": "2020-06-26",
        "warranty": "2025-06-26",
        "maintenance_plan": "Plano PM-HVAC-07",
        "last_maintenance": "2026-02-22",
        "next_maintenance": "2026-03-15",
        "last_preventive": "2026-02-22",
        "next_preventive": "2026-03-15",
        "last_corrective": "2026-01-19",
        "mtbf": "144 h",
        "mttr": "3,1 h",
        "availability": "95,4%",
        "owner": "Ana Lopes",
        "open_work_orders": 1,
        "recent_failures": 1,
        "without_plan": False,
        "has_open_work_order": True,
        "failure_recidivism": "Media",
        "risk_level": "Moderado",
        "impact": "Afeta conforto térmico da área com maior circulação.",
        "technical_notes": "Verificar drenagem de bandeja e reaperto de bornes trimestralmente.",
        "technical_specs": {"tensao": "380 V", "potencia": "22 kW", "capacidade": "30 TR"},
        "maintenance_summary": {"interventions": 8, "downtime": "11,2 h", "plan_adherence": "88%", "trend": "Estavel"},
        "history": [
            {"timestamp": "10/03 14:20", "type": "Preventiva reprogramada", "description": "Ajuste de agenda por indisponibilidade de acesso ao telhado.", "owner": "Ana Lopes", "reference": "PM-HVAC-07"},
            {"timestamp": "22/02 08:40", "type": "Preventiva executada", "description": "Higienização de filtros e medição de corrente.", "owner": "Equipe HVAC", "reference": "PM-HVAC-07"},
        ],
        "alerts": [
            {"severity": "warning", "title": "Preventiva crítica na janela", "description": "A próxima preventiva vence em 3 dias."},
        ],
    },
    {
        "code": "ESTEIRA-ERG-12",
        "name": "Esteira Ergometrica 12",
        "description": "Equipamento de cardio com alto uso diário em horário de pico.",
        "category": "Fitness",
        "subcategory": "Esteira",
        "manufacturer": "Movement",
        "model": "RT250",
        "serial_number": "MV-RT250-2218",
        "client": "Academia Exemplo",
        "site": "Unidade Centro",
        "sector": "Cardio Floor",
        "criticality": "Alta",
        "operational_status": "Parado",
        "condition": "Degradada",
        "installation_date": "2023-01-10",
        "commissioning_date": "2023-01-12",
        "warranty": "2027-01-12",
        "maintenance_plan": "Plano PM-CARDIO-12",
        "last_maintenance": "2026-02-14",
        "next_maintenance": "2026-03-13",
        "last_preventive": "2026-02-14",
        "next_preventive": "2026-03-13",
        "last_corrective": "2026-03-12",
        "mtbf": "72 h",
        "mttr": "2,2 h",
        "availability": "89,7%",
        "owner": "Juliana Costa",
        "open_work_orders": 2,
        "recent_failures": 4,
        "without_plan": False,
        "has_open_work_order": True,
        "failure_recidivism": "Alta",
        "risk_level": "Alto",
        "impact": "Equipamento indisponível em zona com maior uso e forte impacto de experiência do cliente.",
        "technical_notes": "Revisar conjunto de placa e capacitor; avaliar substituição programada.",
        "technical_specs": {"tensao": "220 V", "potencia": "3 kW", "capacidade": "180 kg"},
        "maintenance_summary": {"interventions": 14, "downtime": "17,4 h", "plan_adherence": "86%", "trend": "Piorando"},
        "history": [
            {"timestamp": "12/03 08:10", "type": "Falha registrada", "description": "Falha de partida e desarme ao iniciar corrida.", "owner": "Ana Lopes", "reference": "FE-0093"},
            {"timestamp": "12/03 08:24", "type": "OS aberta", "description": "Corretiva emergencial para placa e sistema de acionamento.", "owner": "Juliana Costa", "reference": "OS-2026-0151"},
            {"timestamp": "14/02 07:50", "type": "Preventiva executada", "description": "Lubrificação, alinhamento e inspeção de correia.", "owner": "Equipe Fitness", "reference": "PM-CARDIO-12"},
        ],
        "alerts": [
            {"severity": "critical", "title": "Ativo parado em área de alta demanda", "description": "Aguardando diagnóstico definitivo da placa de potência."},
            {"severity": "critical", "title": "Falha reincidente", "description": "Quarta falha relacionada ao sistema de partida em 60 dias."},
        ],
    },
    {
        "code": "BIKE-SPIN-07",
        "name": "Bike de Spinning 07",
        "description": "Bike indoor de sala coletiva com uso intensivo em aulas.",
        "category": "Fitness",
        "subcategory": "Bike",
        "manufacturer": "Schwinn",
        "model": "IC8",
        "serial_number": "SC-IC8-8740",
        "client": "Academia Exemplo",
        "site": "Unidade Sul",
        "sector": "Studio Bike",
        "criticality": "Media",
        "operational_status": "Operacional",
        "condition": "Saudavel",
        "installation_date": "2024-02-11",
        "commissioning_date": "2024-02-14",
        "warranty": "2027-02-14",
        "maintenance_plan": "Plano PM-BIKE-04",
        "last_maintenance": "2026-02-28",
        "next_maintenance": "2026-03-28",
        "last_preventive": "2026-02-28",
        "next_preventive": "2026-03-28",
        "last_corrective": "2025-12-17",
        "mtbf": "410 h",
        "mttr": "1,1 h",
        "availability": "99,1%",
        "owner": "Equipe Fitness",
        "open_work_orders": 0,
        "recent_failures": 0,
        "without_plan": False,
        "has_open_work_order": False,
        "failure_recidivism": "Baixa",
        "risk_level": "Baixo",
        "impact": "Impacto localizado e facilmente remanejável.",
        "technical_notes": "Sem apontamentos críticos. Manter rotina mensal de torque e limpeza.",
        "technical_specs": {"tensao": "N/A", "potencia": "N/A", "capacidade": "150 kg"},
        "maintenance_summary": {"interventions": 2, "downtime": "1,2 h", "plan_adherence": "100%", "trend": "Estavel"},
        "history": [
            {"timestamp": "28/02 09:40", "type": "Preventiva executada", "description": "Ajuste de resistência e reaperto estrutural.", "owner": "Equipe Fitness", "reference": "PM-BIKE-04"},
        ],
        "alerts": [],
    },
    {
        "code": "COMPRESSOR-AR-01",
        "name": "Compressor de Ar Principal",
        "description": "Compressor para rede de utilidades pneumáticas do laboratório.",
        "category": "Utilidades",
        "subcategory": "Compressor",
        "manufacturer": "Atlas Copco",
        "model": "GA15",
        "serial_number": "AC-GA15-1091",
        "client": "Laboratorio Exemplo",
        "site": "Laboratorio Campinas",
        "sector": "Casa de Utilidades",
        "criticality": "Alta",
        "operational_status": "Operacional",
        "condition": "Em atencao",
        "installation_date": "2019-08-09",
        "commissioning_date": "2019-08-16",
        "warranty": "2024-08-16",
        "maintenance_plan": "Plano PM-UTIL-02",
        "last_maintenance": "2026-02-20",
        "next_maintenance": "2026-03-22",
        "last_preventive": "2026-02-20",
        "next_preventive": "2026-03-22",
        "last_corrective": "2026-01-29",
        "mtbf": "104 h",
        "mttr": "3,9 h",
        "availability": "94,3%",
        "owner": "Lucas Neri",
        "open_work_orders": 1,
        "recent_failures": 2,
        "without_plan": False,
        "has_open_work_order": True,
        "failure_recidivism": "Media",
        "risk_level": "Moderado",
        "impact": "Afeta linha de utilidades e testes pneumáticos.",
        "technical_notes": "Monitorar vazamento na linha e revisar kit de vedação.",
        "technical_specs": {"tensao": "380 V", "potencia": "15 kW", "capacidade": "2.4 m3/min"},
        "maintenance_summary": {"interventions": 9, "downtime": "13,7 h", "plan_adherence": "90%", "trend": "Estavel"},
        "history": [
            {"timestamp": "29/01 17:10", "type": "OS concluida", "description": "Substituição de kit de vedação e ajuste de pressão.", "owner": "Lucas Neri", "reference": "OS-2026-0102"},
        ],
        "alerts": [
            {"severity": "warning", "title": "Falha recente", "description": "Ocorrência de perda de pressão nas últimas 6 semanas."},
        ],
    },
    {
        "code": "INVERSOR-WEG-EST-03",
        "name": "Inversor WEG Esteira 03",
        "description": "Acionamento eletrônico da linha de transporte técnico.",
        "category": "Automacao",
        "subcategory": "Inversor de frequencia",
        "manufacturer": "WEG",
        "model": "CFW500",
        "serial_number": "WEG-CFW-5541",
        "client": "Smart Control Brasil",
        "site": "Planta Maua",
        "sector": "Linha de Envase",
        "criticality": "Critica",
        "operational_status": "Operacional",
        "condition": "Em atencao",
        "installation_date": "2021-11-08",
        "commissioning_date": "2021-11-12",
        "warranty": "2026-11-12",
        "maintenance_plan": "Plano PM-AUT-09",
        "last_maintenance": "2026-02-18",
        "next_maintenance": "2026-03-20",
        "last_preventive": "2026-02-18",
        "next_preventive": "2026-03-20",
        "last_corrective": "2026-01-30",
        "mtbf": "126 h",
        "mttr": "2,7 h",
        "availability": "96,1%",
        "owner": "Bruno Salles",
        "open_work_orders": 1,
        "recent_failures": 1,
        "without_plan": False,
        "has_open_work_order": True,
        "failure_recidivism": "Baixa",
        "risk_level": "Alto",
        "impact": "Pode interromper célula crítica de produção e gerar perda de throughput.",
        "technical_notes": "Planejar varredura termográfica e revisar ventilação do painel.",
        "technical_specs": {"tensao": "380 V", "potencia": "7.5 kW", "capacidade": "10 A"},
        "maintenance_summary": {"interventions": 5, "downtime": "6,8 h", "plan_adherence": "92%", "trend": "Melhorando"},
        "history": [
            {"timestamp": "30/01 13:45", "type": "OS concluida", "description": "Troca de ventilador interno e atualização de parâmetros.", "owner": "Bruno Salles", "reference": "OS-2026-0109"},
        ],
        "alerts": [
            {"severity": "info", "title": "Inspeção programada", "description": "Termografia do painel agendada para a próxima semana."},
        ],
    },
    {
        "code": "CLP-LINHA-ENV-02",
        "name": "CLP Linha de Envase 02",
        "description": "Controlador lógico programável da célula secundária de envase.",
        "category": "Automacao",
        "subcategory": "CLP",
        "manufacturer": "Siemens",
        "model": "S7-1200",
        "serial_number": "SI-S71200-3009",
        "client": "Smart Control Brasil",
        "site": "Planta Maua",
        "sector": "Painel Central",
        "criticality": "Alta",
        "operational_status": "Operacional",
        "condition": "Saudavel",
        "installation_date": "2022-03-04",
        "commissioning_date": "2022-03-09",
        "warranty": "2027-03-09",
        "maintenance_plan": "",
        "last_maintenance": "2025-12-02",
        "next_maintenance": "Nao vinculada",
        "last_preventive": "2025-12-02",
        "next_preventive": "Nao vinculada",
        "last_corrective": "2025-08-21",
        "mtbf": "520 h",
        "mttr": "1,9 h",
        "availability": "99,4%",
        "owner": "Equipe Automacao",
        "open_work_orders": 0,
        "recent_failures": 0,
        "without_plan": True,
        "has_open_work_order": False,
        "failure_recidivism": "Baixa",
        "risk_level": "Moderado",
        "impact": "Perda da lógica de uma célula de envase com impacto relevante em produção.",
        "technical_notes": "Ativo sem plano preventivo formal; incluir backup validado e inspeção semestral.",
        "technical_specs": {"tensao": "24 Vdc", "potencia": "N/A", "capacidade": "CPU 1214C"},
        "maintenance_summary": {"interventions": 1, "downtime": "0,9 h", "plan_adherence": "0%", "trend": "Sem baseline"},
        "history": [
            {"timestamp": "02/12 15:30", "type": "Inspecao realizada", "description": "Backup de programa e teste de I/O.", "owner": "Equipe Automacao", "reference": "INSP-220"},
        ],
        "alerts": [
            {"severity": "warning", "title": "Ativo sem plano preventivo", "description": "Inserir rotina formal de backup, inspeção e limpeza de painel."},
        ],
    },
    {
        "code": "FORNO-LAB-01",
        "name": "Forno de Secagem LAB 01",
        "description": "Forno de bancada para secagem e estabilização térmica de amostras.",
        "category": "Laboratorio",
        "subcategory": "Forno",
        "manufacturer": "Fanem",
        "model": "315 SE",
        "serial_number": "FA-315SE-0097",
        "client": "Laboratorio Exemplo",
        "site": "Laboratorio Campinas",
        "sector": "Bancada Térmica",
        "criticality": "Media",
        "operational_status": "Operacional",
        "condition": "Saudavel",
        "installation_date": "2023-09-01",
        "commissioning_date": "2023-09-05",
        "warranty": "2026-09-05",
        "maintenance_plan": "Plano PM-LAB-03",
        "last_maintenance": "2026-01-15",
        "next_maintenance": "2026-04-15",
        "last_preventive": "2026-01-15",
        "next_preventive": "2026-04-15",
        "last_corrective": "Nunca",
        "mtbf": "680 h",
        "mttr": "0,7 h",
        "availability": "99,8%",
        "owner": "Equipe LAB",
        "open_work_orders": 0,
        "recent_failures": 0,
        "without_plan": False,
        "has_open_work_order": False,
        "failure_recidivism": "Baixa",
        "risk_level": "Baixo",
        "impact": "Impacto limitado e facilmente remanejável.",
        "technical_notes": "Operação estável, manter calibração anual.",
        "technical_specs": {"tensao": "220 V", "potencia": "1.8 kW", "capacidade": "315 L"},
        "maintenance_summary": {"interventions": 2, "downtime": "0,8 h", "plan_adherence": "100%", "trend": "Estavel"},
        "history": [
            {"timestamp": "15/01 10:12", "type": "Preventiva executada", "description": "Verificação de resistência e calibração térmica.", "owner": "Equipe LAB", "reference": "PM-LAB-03"},
        ],
        "alerts": [],
    },
    {
        "code": "EXAUSTOR-IND-05",
        "name": "Exaustor Industrial 05",
        "description": "Sistema de exaustão da área de mistura e preparação.",
        "category": "Utilidades",
        "subcategory": "Exaustor",
        "manufacturer": "Ventisilva",
        "model": "VX900",
        "serial_number": "VS-VX900-4411",
        "client": "Smart Control Brasil",
        "site": "Planta Maua",
        "sector": "Mistura",
        "criticality": "Alta",
        "operational_status": "Operacao degradada",
        "condition": "Degradada",
        "installation_date": "2018-05-22",
        "commissioning_date": "2018-05-29",
        "warranty": "2023-05-29",
        "maintenance_plan": "Plano PM-UTIL-08",
        "last_maintenance": "2026-02-03",
        "next_maintenance": "2026-03-14",
        "last_preventive": "2026-02-03",
        "next_preventive": "2026-03-14",
        "last_corrective": "2026-03-01",
        "mtbf": "118 h",
        "mttr": "3,7 h",
        "availability": "92,7%",
        "owner": "Rafael Nunes",
        "open_work_orders": 1,
        "recent_failures": 2,
        "without_plan": False,
        "has_open_work_order": True,
        "failure_recidivism": "Media",
        "risk_level": "Alto",
        "impact": "Afeta segurança operacional e condição ambiental da área.",
        "technical_notes": "Vibração crescente no conjunto motoventilador; avaliar alinhamento e rolamentos.",
        "technical_specs": {"tensao": "380 V", "potencia": "11 kW", "capacidade": "9000 m3/h"},
        "maintenance_summary": {"interventions": 7, "downtime": "14,6 h", "plan_adherence": "89%", "trend": "Piorando"},
        "history": [
            {"timestamp": "01/03 16:48", "type": "OS aberta", "description": "Vibração acima do limite e ruído anormal.", "owner": "Rafael Nunes", "reference": "OS-2026-0126"},
            {"timestamp": "03/02 08:20", "type": "Preventiva executada", "description": "Inspeção de rolamentos e reaperto estrutural.", "owner": "Equipe Utilidades", "reference": "PM-UTIL-08"},
        ],
        "alerts": [
            {"severity": "critical", "title": "Condição degradada", "description": "Ativo com vibração acima do limite e impacto em segurança operacional."},
        ],
    },
]


def _normalize(value):
    return str(value).strip().lower()


def get_asset_options(records=None):
    records = records or ASSET_RECORDS
    return {
        "clients": sorted({asset["client"] for asset in records}),
        "sites": sorted({asset["site"] for asset in records}),
        "categories": sorted({asset["category"] for asset in records}),
        "criticalities": sorted({asset["criticality"] for asset in records}),
        "statuses": sorted({asset["operational_status"] for asset in records}),
        "conditions": sorted({asset["condition"] for asset in records}),
        "manufacturers": sorted({asset["manufacturer"] for asset in records}),
    }


def filter_assets(filters=None, tenant_context=None):
    filters = filters or {}
    queryset = filter_records_for_scope(deepcopy(ASSET_RECORDS), tenant_context or {})
    search = _normalize(filters.get("search", ""))
    if search:
        queryset = [
            asset
            for asset in queryset
            if search in _normalize(asset["code"])
            or search in _normalize(asset["name"])
            or search in _normalize(asset["description"])
        ]

    equality_map = {
        "client": "client",
        "site": "site",
        "category": "category",
        "criticality": "criticality",
        "status": "operational_status",
        "condition": "condition",
        "manufacturer": "manufacturer",
    }
    for filter_key, asset_key in equality_map.items():
        value = filters.get(filter_key, "")
        if value:
            queryset = [asset for asset in queryset if asset[asset_key] == value]

    if filters.get("preventive") == "without":
        queryset = [asset for asset in queryset if asset["without_plan"]]
    elif filters.get("preventive") == "with":
        queryset = [asset for asset in queryset if not asset["without_plan"]]

    if filters.get("work_orders") == "with":
        queryset = [asset for asset in queryset if asset["has_open_work_order"]]
    elif filters.get("work_orders") == "without":
        queryset = [asset for asset in queryset if not asset["has_open_work_order"]]

    return queryset


def get_asset_listing_context(filters=None, tenant_context=None):
    filters = filters or {}
    all_assets = filter_records_for_scope(deepcopy(ASSET_RECORDS), tenant_context or {})
    assets = filter_assets(filters, tenant_context=tenant_context)
    options = get_asset_options(all_assets)
    return {
        "page_actions": [
            {
                "label": "Novo ativo",
                "route_name": "admin-shell:smart-system-customer-equipment-create",
                "permission_domain": "assets",
                "permission_action": "create",
            },
            {"label": "Importar ativos", "href": "#importar-ativos", "permission_domain": "assets", "permission_action": "create"},
            {"label": "Exportar lista", "href": "#exportar-ativos", "permission_domain": "assets", "permission_action": "export"},
            {"label": "Ver criticidade", "href": "#criticidade", "permission_domain": "assets", "permission_action": "view"},
        ],
        "asset_filters": [
            {"name": "search", "label": "Busca", "type": "search", "value": filters.get("search", ""), "placeholder": "Nome, tag ou codigo"},
            {"name": "client", "label": "Cliente", "type": "select", "value": filters.get("client", ""), "options": options["clients"]},
            {"name": "site", "label": "Site / unidade", "type": "select", "value": filters.get("site", ""), "options": options["sites"]},
            {"name": "category", "label": "Categoria", "type": "select", "value": filters.get("category", ""), "options": options["categories"]},
            {"name": "criticality", "label": "Criticidade", "type": "select", "value": filters.get("criticality", ""), "options": options["criticalities"]},
            {"name": "status", "label": "Status operacional", "type": "select", "value": filters.get("status", ""), "options": options["statuses"]},
            {"name": "condition", "label": "Condicao", "type": "select", "value": filters.get("condition", ""), "options": options["conditions"]},
            {"name": "manufacturer", "label": "Fabricante", "type": "select", "value": filters.get("manufacturer", ""), "options": options["manufacturers"]},
            {"name": "preventive", "label": "Plano preventivo", "type": "select", "value": filters.get("preventive", ""), "options": ["with", "without"]},
            {"name": "work_orders", "label": "OS aberta", "type": "select", "value": filters.get("work_orders", ""), "options": ["with", "without"]},
        ],
        "asset_kpis": [
            {"label": "Total de ativos", "value": str(len(all_assets)), "tone": "indigo"},
            {"label": "Ativos operacionais", "value": str(sum(1 for asset in all_assets if asset["operational_status"] == "Operacional")), "tone": "emerald"},
            {"label": "Ativos em atencao", "value": str(sum(1 for asset in all_assets if asset["condition"] == "Em atencao")), "tone": "amber"},
            {"label": "Ativos criticos", "value": str(sum(1 for asset in all_assets if asset["criticality"] == "Critica")), "tone": "red"},
            {"label": "Ativos parados", "value": str(sum(1 for asset in all_assets if asset["operational_status"] == "Parado")), "tone": "orange"},
            {"label": "Sem plano preventivo", "value": str(sum(1 for asset in all_assets if asset["without_plan"])), "tone": "violet"},
            {"label": "Com OS aberta", "value": str(sum(1 for asset in all_assets if asset["has_open_work_order"])), "tone": "sky"},
            {"label": "Falha recente", "value": str(sum(1 for asset in all_assets if asset["recent_failures"] > 0)), "tone": "rose"},
        ],
        "assets": assets,
        "filtered_count": len(assets),
        "total_count": len(all_assets),
    }


def get_asset_by_code(asset_code, tenant_context=None):
    target = _normalize(asset_code)
    for asset in ASSET_RECORDS:
        if _normalize(asset["code"]) == target and record_matches_scope(asset, tenant_context or {}):
            return deepcopy(asset)
    return None


def get_asset_detail_context(asset_code, tenant_context=None):
    asset = get_asset_by_code(asset_code, tenant_context=tenant_context)
    if asset is None:
        return None
    asset["summary_cards"] = [
        {"label": "Status operacional", "value": asset["operational_status"], "tone": "sky"},
        {"label": "Condicao geral", "value": asset["condition"], "tone": "amber" if asset["condition"] != "Saudavel" else "emerald"},
        {"label": "Criticidade", "value": asset["criticality"], "tone": "red" if asset["criticality"] in {"Alta", "Critica"} else "violet"},
        {"label": "Disponibilidade", "value": asset["availability"], "tone": "emerald"},
        {"label": "Ultima manutencao", "value": asset["last_maintenance"], "tone": "indigo"},
        {"label": "Proxima manutencao", "value": asset["next_maintenance"], "tone": "orange"},
        {"label": "OS abertas", "value": str(asset["open_work_orders"]), "tone": "rose"},
        {"label": "Falhas recentes", "value": str(asset["recent_failures"]), "tone": "red" if asset["recent_failures"] else "emerald"},
        {"label": "Aderencia preventiva", "value": asset["maintenance_summary"]["plan_adherence"], "tone": "cyan"},
    ]
    asset["page_actions"] = [
        {"label": "Abrir OS", "href": "#abrir-os", "permission_domain": "work_orders", "permission_action": "create"},
        {"label": "Abrir preventiva", "href": f"/app/smart-system/preventives/?search={asset['code']}", "permission_domain": "preventive_plans", "permission_action": "view"},
        {"label": "Ver falhas", "href": f"/app/smart-system/failures/?search={asset['code']}", "permission_domain": "failures", "permission_action": "view"},
        {"label": "Ver checklists", "href": f"/app/smart-system/checklists/?search={asset['code']}", "permission_domain": "checklists", "permission_action": "view"},
        {"label": "Ver pecas", "href": f"/app/smart-system/parts/?asset={asset['code']}", "permission_domain": "inventory", "permission_action": "view"},
        {"label": "Gerar ficha tecnica", "href": f"/app/smart-system/reports/asset-summary/{asset['code']}/", "permission_domain": "reports", "permission_action": "view"},
        {"label": "Registrar falha", "href": "#registrar-falha", "permission_domain": "failures", "permission_action": "create"},
        {"label": "Lancar inspecao", "href": "#inspecao", "permission_domain": "checklists", "permission_action": "execute"},
        {"label": "Editar ativo", "href": "#editar-ativo", "permission_domain": "assets", "permission_action": "update"},
        {"label": "Ver OS do ativo", "href": f"/app/smart-system/work-orders/?search={asset['code']}", "permission_domain": "work_orders", "permission_action": "view"},
        {"label": "Ver historico completo", "href": "#historico", "permission_domain": "assets", "permission_action": "view"},
        {"label": "Baixar PDF", "href": f"/app/smart-system/reports/asset-summary/{asset['code']}/download/", "permission_domain": "reports", "permission_action": "export"},
    ]
    asset["quick_actions"] = [
        {"label": "Nova ordem de servico", "context": "Intervencao corretiva ou inspeção", "href": "#abrir-os", "tone": "indigo", "permission_domain": "work_orders", "permission_action": "create"},
        {"label": "Plano preventivo", "context": "Acompanhar cobertura e recorrencia", "href": f"/app/smart-system/preventives/?search={asset['code']}", "tone": "teal", "permission_domain": "preventive_plans", "permission_action": "view"},
        {"label": "Historico de falhas", "context": "Recorrencia, RCA e impacto operacional", "href": f"/app/smart-system/failures/?search={asset['code']}", "tone": "orange", "permission_domain": "failures", "permission_action": "view"},
        {"label": "Checklists executaveis", "context": "Inspecao e execucao padronizada", "href": f"/app/smart-system/checklists/?search={asset['code']}", "tone": "violet", "permission_domain": "checklists", "permission_action": "execute"},
        {"label": "Sobressalentes", "context": "Pecas e itens de reposicao associados", "href": f"/app/smart-system/parts/?asset={asset['code']}", "tone": "amber", "permission_domain": "inventory", "permission_action": "view"},
        {"label": "Registrar falha", "context": "Evento tecnico e RCA inicial", "href": "#registrar-falha", "tone": "red", "permission_domain": "failures", "permission_action": "create"},
        {"label": "Adicionar observacao", "context": "Contexto tecnico do ativo", "href": "#observacao", "tone": "sky", "permission_domain": "assets", "permission_action": "update"},
        {"label": "Programar preventiva", "context": "Janela e cronograma do plano", "href": "#preventiva", "tone": "emerald", "permission_domain": "preventive_plans", "permission_action": "create"},
        {"label": "Consultar OS vinculadas", "context": "Filtrar ordens por tag do ativo", "href": f"/app/smart-system/work-orders/?search={asset['code']}", "tone": "rose", "permission_domain": "work_orders", "permission_action": "view"},
        {"label": "Vincular checklist", "context": "Padronizacao de inspeção", "href": "#checklist", "tone": "violet", "permission_domain": "checklists", "permission_action": "update"},
        {"label": "Anexar documento", "context": "Manual, laudo ou foto tecnica", "href": "#documento", "tone": "amber", "permission_domain": "assets", "permission_action": "update"},
    ]
    asset["risk_panel"] = [
        {"label": "Impacto operacional", "value": asset["impact"]},
        {"label": "Nivel de risco", "value": asset["risk_level"]},
        {"label": "Reincidencia de falha", "value": asset["failure_recidivism"]},
        {"label": "Necessidade de intervencao", "value": "Imediata" if asset["condition"] in {"Critica", "Degradada"} else "Planejada"},
    ]
    return asset
