# Generated by Django 6.0.4 on 2026-05-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ("media_library", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='título')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('brand', models.CharField(max_length=120, verbose_name='fabricante/marca')),
                ('supplier_name', models.CharField(max_length=180, verbose_name='nome do fornecedor/parceiro')),
                ('category', models.CharField(max_length=120, verbose_name='categoria')),
                ('short_description', models.CharField(max_length=500, verbose_name='resumo curto')),
                ('description', models.TextField(blank=True, verbose_name='descrição completa')),
                ('application_area', models.CharField(max_length=300, verbose_name='área de aplicação')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo no catálogo')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='destacar na home')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_products_featured', to='media_library.mediaasset', verbose_name='imagem destacada')),
            ],
            options={
                'verbose_name': 'produto técnico',
                'verbose_name_plural': 'produtos técnicos do catálogo',
                'ordering': ('-is_featured', '-updated_at'),
            },
        ),
    ]
