# Generated by Django 6.0.4 on 2026-05-13 23:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_digital_twin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaltwinsignal',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
